-- The contraction half of retiring the legacy per-user plan surface
-- (plans/phase-1/30-stripe-billing-platform §11 "Contract legacy schema only after the compatibility window").
-- Generated by `drizzle-kit generate`; the comments are added, the statements are untouched.
--
-- The code stopped reading and writing these three tables on 2026-08-03: `schema.ts` no longer declares them,
-- `/api/plans/request-upgrade`, `/api/me/plan-changes` and `/admin/plan-requests` are gone, and granting a tier
-- by hand now goes through `organization_entitlements` (`repositories/operator-grants.ts` +
-- `drizzle/0141`'s SECURITY DEFINER function), against the organization that is actually entitled rather than a
-- user who may belong to several.
--
-- `CASCADE` is what drizzle generates, and it was checked rather than trusted. Against the live database,
-- immediately before this migration was written:
--
--   plans: 0 rows / plan_changes: 0 rows / plan_requests: 0 rows
--   incoming foreign keys: none
--   views referencing them: none
--   functions referencing them: none   (`sync_personal_organization_entitlement` reads organization_members)
--   triggers on them: none
--   a dry-run `DROP TABLE ... CASCADE` for all three inside a rolled-back transaction: no dependency error
--
-- So CASCADE takes nothing with it here. It stays because that is what the generator emits, and hand-editing
-- generated statements to prove a point is how migrations drift from their snapshot.
--
-- `plan_changes` deserves the specific note: it never had a writer at all. Nothing in the application's history
-- ever inserted a row, so nothing is being discarded — the "plan history" it appeared to hold was empty by
-- construction. The audit trail that does exist is `security_audit_events`, where every operator grant is
-- recorded as `admin.user.entitlement-grant` against the organization, carrying `onBehalfOfUserId`.
DROP TABLE "plan_changes" CASCADE;--> statement-breakpoint
DROP TABLE "plan_requests" CASCADE;--> statement-breakpoint
DROP TABLE "plans" CASCADE;
