-- The solution source register is empty in production, like `search_sources` was.
--
-- `0126`, `0127`, `0132` and `0139` each seed rows into `solution_sources` in the same file that
-- creates or extends it. Locally that leaves nineteen. Production has zero — the same symptom, and the
-- same cause: a baselined drizzle journal marked those migrations applied without executing them, so
-- every table whose rows arrive by seed came up empty. `0163` repaired the search register; this one
-- repairs the catalogue behind `solution-catalog.ts`, which reads `solutionSources` at runtime.
--
-- Nothing observable changes today, and that is expected: all nineteen are `enabled = false` by design,
-- exactly as the register intends. What changes is that an operator can *see* them — the administration
-- surface lists sources to switch on, and with no rows there is nothing to switch. A source cannot be
-- enabled from the UI when the row that would carry the flag does not exist.
--
-- Generated from the live local table rather than reassembled from the four original files. Extracting
-- the statements by hand is what nearly broke `0163`: splitting on `;` produced eight fragments from
-- three statements, because the `register_notes` prose contains semicolons. Here PostgreSQL emitted the
-- literals through `quote_nullable`, so the escaping (`Adzuna''s`) is the database's own.
--
-- `created_at`/`updated_at` are omitted so the defaults apply — these rows are being created now, and
-- claiming otherwise would be a lie in the audit trail.
--
-- One value was corrected on the way through: `generic_human_roles.homepage_url` pointed at
-- `builderhunt.eduardoinerarte.dk`, retired on 2026-08-10 and now answering 503. It names
-- `builderhunt.dev`.
--
-- Idempotent — `ON CONFLICT ("key") DO NOTHING` — so this is a no-op wherever the register is populated,
-- and it never overwrites an operator's decision to enable a source.

INSERT INTO "solution_sources" (key, kind, label, homepage_url, enabled, allowed_fields, geography, owner_contact, rate_limit_per_hour, refresh_interval_hours, retention_days, terms_reviewed_at, terms_reviewed_by, register_notes, attribution_required, attribution_text, attribution_url, max_requests_per_day) VALUES
  ('linkedin_profiles', 'external_link_only', 'LinkedIn (link out only)', 'https://www.linkedin.com', false, '[]'::jsonb, 'global', NULL, NULL, NULL, NULL, NULL::timestamptz, NULL, 'https://www.linkedin.com/legal/crawling-terms prohibits automated collection and no permission is on file. Outbound links only — nothing fetched from this host is stored.', false, NULL, NULL, NULL),
  ('adzuna_jobs', 'feed', 'Adzuna', 'https://api.adzuna.com', false, '["roleTitle", "companyName", "area", "summary", "postingUrl", "publishedAt", "remote", "employmentType", "seniority", "salaryMin", "salaryMax", "salaryCurrency", "tags"]'::jsonb, 'global', NULL, 250, 24, 60, NULL::timestamptz, NULL, 'NEVER RUN. Shape from the published field list on developer.adzuna.com; needs ADZUNA_APP_ID and ADZUNA_APP_KEY. Country is part of the path (ADZUNA_COUNTRY, default gb) — a wrong country returns a valid-looking page of the wrong market. salary_is_predicted marks Adzuna''s own model output rather than the employer''s figure, and a predicted salary is dropped rather than stored: it would feed a cost estimate the employer never stated.', false, NULL, NULL, NULL),
  ('arbeitnow_jobs', 'feed', 'Arbeitnow (EU + remote)', 'https://www.arbeitnow.com', false, '["roleTitle", "companyName", "area", "summary", "postingUrl", "publishedAt", "remote", "employmentType", "seniority", "salaryMin", "salaryMax", "salaryCurrency", "tags"]'::jsonb, 'eu', NULL, 60, 6, 90, NULL::timestamptz, NULL, 'Public job-board API, no auth (https://www.arbeitnow.com/blog/job-board-api). Probed 2026-08-01: 175 postings, no stated attribution requirement. Europe and remote, with a visa_sponsorship filter. arbeitnow.com 301-redirects to www.arbeitnow.com.', false, NULL, NULL, 24),
  ('arbeitsagentur_jobs', 'feed', 'Bundesagentur für Arbeit', 'https://rest.arbeitsagentur.de', false, '["roleTitle", "companyName", "area", "summary", "postingUrl", "publishedAt", "remote", "employmentType", "seniority", "salaryMin", "salaryMax", "salaryCurrency", "tags"]'::jsonb, 'DE', NULL, 300, 12, 60, NULL::timestamptz, NULL, 'Probed live 2026-08-02 with X-API-Key: jobboerse-jobsuche, the public client key their own web app sends. The search payload carries no description at all — only title, employer and place — so summary is null rather than padded with the title. Full text would need a second call per posting, which is a rate-limit decision nobody has made.', false, NULL, NULL, NULL),
  ('france_travail_jobs', 'feed', 'France Travail', 'https://api.francetravail.io', false, '["roleTitle", "companyName", "area", "summary", "postingUrl", "publishedAt", "remote", "employmentType", "seniority", "salaryMin", "salaryMax", "salaryCurrency", "tags"]'::jsonb, 'FR', NULL, 200, 24, 60, NULL::timestamptz, NULL, 'NEVER RUN, and not yet runnable. Shape from the published Offres d''emploi v2 documentation; a probe on 2026-08-02 returned 401. Their auth is OAuth2 client-credentials, so the token is short-lived and cannot be a static environment variable — the adapter reads FRANCE_TRAVAIL_ACCESS_TOKEN as a bearer, which means something else must mint it, and that exchange is NOT implemented. salaire.libelle is free text and is deliberately not regex-mined.', false, NULL, NULL, NULL),
  ('himalayas_jobs', 'feed', 'Himalayas', 'https://himalayas.app', false, '["roleTitle", "companyName", "area", "summary", "postingUrl", "publishedAt", "remote", "employmentType", "seniority", "salaryMin", "salaryMax", "salaryCurrency", "tags"]'::jsonb, 'global', NULL, 60, 6, 90, NULL::timestamptz, NULL, 'Public JSON API, no auth. Probed 2026-08-01: 96218 postings reported, paginated by offset/limit. Richest structured fields of the four — employment type, seniority, salary band, location and timezone restrictions.', false, NULL, NULL, 24),
  ('infojobs_jobs', 'feed', 'InfoJobs', 'https://api.infojobs.net', false, '["roleTitle", "companyName", "area", "summary", "postingUrl", "publishedAt", "remote", "employmentType", "seniority", "salaryMin", "salaryMax", "salaryCurrency", "tags"]'::jsonb, 'ES', NULL, 200, 24, 60, NULL::timestamptz, NULL, 'NEVER RUN. Shape from the published v9 offer documentation; a probe on 2026-08-02 returned 401. Auth is HTTP Basic over INFOJOBS_CLIENT_ID:INFOJOBS_CLIENT_SECRET, built at request time rather than stored pre-encoded.', false, NULL, NULL, NULL),
  ('jobicy_jobs', 'feed', 'Jobicy', 'https://jobicy.com', false, '["roleTitle", "companyName", "area", "summary", "postingUrl", "publishedAt", "remote", "employmentType", "seniority", "salaryMin", "salaryMax", "salaryCurrency", "tags"]'::jsonb, 'global', NULL, 60, 6, 90, NULL::timestamptz, NULL, 'Public REST API v2, no auth. Their terms, served in the response body: "Please ensure Jobicy is clearly credited with a direct link to the source, and all application buttons redirect to the original job URL provided in this feed." The second half is a product constraint, not just a credit: an apply button must go to their URL. Probed 2026-08-01.', true, 'Jobs from Jobicy', 'https://jobicy.com', 24),
  ('jobindex_roles', 'feed', 'Jobindex open roles (DK)', 'https://www.jobindex.dk', false, '["roleTitle", "companyName", "area", "summary", "postingUrl", "publishedAt"]'::jsonb, 'dk', NULL, 24, 24, 90, NULL::timestamptz, NULL, 'Official RSS feed. Yields human_role components describing roles Danish employers are hiring for — demand-side market signal, not candidate data. Company names are corporate identifiers, not personal data. No capability claims: a job ad states what an employer wants, never what anyone can do.', false, NULL, NULL, NULL),
  ('jobtech_dev_jobs', 'feed', 'JobTech Dev (Arbetsförmedlingen)', 'https://jobsearch.api.jobtechdev.se', false, '["roleTitle", "companyName", "area", "summary", "postingUrl", "publishedAt", "remote", "employmentType", "seniority", "salaryMin", "salaryMax", "salaryCurrency", "tags"]'::jsonb, 'SE', NULL, 600, 12, 60, NULL::timestamptz, NULL, 'Swedish Public Employment Service open API. Probed live 2026-08-02: no key required, full hit shape inspected and the parser written against it. JOBTECH_DEV_API_KEY is optional and raises limits only. Taxonomy labels are stored, never concept ids — an id like fg7B_yov_smw matches nothing a person would type.', false, NULL, NULL, NULL),
  ('mcp_servers_registry', 'feed', 'MCP server directory feed', 'https://modelcontextprotocol.io', false, '["name", "description", "capabilities"]'::jsonb, 'global', NULL, 60, 24, 180, NULL::timestamptz, NULL, 'Published directory feed. No adapter implemented yet, so this source is registered but never ingests. Enabling it has no effect until one lands.', false, NULL, NULL, NULL),
  ('remoteok_jobs', 'feed', 'Remote OK', 'https://remoteok.com', false, '["roleTitle", "companyName", "area", "summary", "postingUrl", "publishedAt", "remote", "employmentType", "seniority", "salaryMin", "salaryMax", "salaryCurrency", "tags"]'::jsonb, 'global', NULL, 60, 6, 90, NULL::timestamptz, NULL, 'Public API, no auth. Their terms, served in the response body: "Please link back (with follow, and without nofollow!) to the URL on Remote OK and mention Remote OK as a source ... If you do not we''ll have to suspend API access." The logo is a registered trademark and must not be used; the name may be. Probed 2026-08-01: 100 postings. Note their titles arrive double-encoded (UTF-8 read as latin-1) for non-ASCII languages — the adapter repairs this.', true, 'Jobs from Remote OK', 'https://remoteok.com', 24),
  ('remotive_jobs', 'feed', 'Remotive', 'https://remotive.com', false, '[]'::jsonb, 'global', NULL, NULL, 24, 90, NULL::timestamptz, NULL, 'NO ADAPTER, and not a technical gap. Their terms, served in the response body, include: "Displaying our jobs in order to collect signups/email addresses to show a listing constitutes a breach of our terms of services." BuilderHunt is a product people sign up for, so whether that clause covers us is a judgement with real consequences (their private API starts at $5k/mo) and belongs to the maintainer, not to this migration. Also: max 4 requests/day, mandatory link-back, and a deliberate 24h delay on the data. allowed_fields is empty so nothing can be stored even if an adapter appeared.', true, 'Jobs from Remotive', 'https://remotive.com', 4),
  ('themuse_jobs', 'feed', 'The Muse', 'https://www.themuse.com', false, '["roleTitle", "companyName", "area", "summary", "postingUrl", "publishedAt", "remote", "employmentType", "seniority", "salaryMin", "salaryMax", "salaryCurrency", "tags"]'::jsonb, 'global', NULL, 100, 12, 60, NULL::timestamptz, NULL, 'Probed live 2026-08-02: page 1 answers without a key and the full result shape was inspected. MUSE_API_KEY raises the rate limit. Descriptions are HTML and go through htmlToPlainText. Remote is inferred from a location named "Flexible / Remote" because there is no flag.', false, NULL, NULL, NULL),
  ('usajobs_jobs', 'feed', 'USAJOBS', 'https://data.usajobs.gov', false, '["roleTitle", "companyName", "area", "summary", "postingUrl", "publishedAt", "remote", "employmentType", "seniority", "salaryMin", "salaryMax", "salaryCurrency", "tags"]'::jsonb, 'US', NULL, 300, 24, 60, NULL::timestamptz, NULL, 'NEVER RUN. Shape from the published SearchResult.SearchResultItems[].MatchedObjectDescriptor envelope; a probe on 2026-08-02 returned 401, which confirms only that Authorization-Key is required. USAJOBS_USER_AGENT is not decoration — their terms require a contact address in the User-Agent. Currency is asserted as USD, the one place it can be without guessing.', false, NULL, NULL, NULL),
  ('huggingface_models', 'official_api', 'Hugging Face model metadata', 'https://huggingface.co', false, '["pipelineTag", "libraryName", "downloads", "likes", "tags"]'::jsonb, 'global', NULL, 600, 24, 180, NULL::timestamptz, NULL, 'Documented public HTTP API (huggingface.co/api/models). Model card fields only. pipeline_tag is mapped to our capability vocabulary by exact lookup; an unmapped tag yields no claim.', false, NULL, NULL, NULL),
  ('npm_registry', 'official_api', 'npm registry metadata', 'https://registry.npmjs.org', false, '["description", "version", "keywords"]'::jsonb, 'global', NULL, 600, 24, 180, NULL::timestamptz, NULL, 'Registry API, the same endpoint every package manager uses. Capabilities come from an exact keyword allowlist, never a fuzzy match.', false, NULL, NULL, NULL),
  ('thehub_startups', 'public_scrape', 'The Hub (Nordic startups)', 'https://thehub.io', false, '[]'::jsonb, 'nordics', NULL, NULL, 24, 90, NULL::timestamptz, NULL, 'NO ADAPTER. thehub.io has an internal JSON endpoint that third-party scrapers use, but an undocumented internal endpoint is not a published API — the same reasoning that keeps LinkedIn adapter-less. Registered as public_scrape so solution_sources_scrape_needs_review_check requires a recorded terms review before it can ever be enabled. Founder names and LinkedIn links appear in its data, which makes it personal data and not merely company data.', false, NULL, NULL, NULL),
  ('generic_human_roles', 'user_submission', 'Authored specialist roles', 'https://builderhunt.dev', false, '["name", "description"]'::jsonb, 'global', NULL, NULL, NULL, NULL, NULL::timestamptz, NULL, 'Authored in-house, not ingested. Provides the generic human_role components the composer pairs with agents when no specific person is required.', false, NULL, NULL, NULL)
ON CONFLICT ("key") DO NOTHING;

-- Existing rows keep the retired hostname, because `ON CONFLICT DO NOTHING` deliberately does not
-- overwrite them — right for operator decisions like `enabled`, wrong for a URL that now answers 503.
-- Scoped to the one field and the one host, so it cannot disturb anything an operator set.
UPDATE "solution_sources"
   SET "homepage_url" = replace("homepage_url", 'https://builderhunt.eduardoinerarte.dk', 'https://builderhunt.dev'),
       "updated_at" = now()
 WHERE "homepage_url" LIKE '%builderhunt.eduardoinerarte.dk%';
