import { createFileRoute } from '@tanstack/react-router'
import { methodNotAllowed } from '~/shared/lib/http/method-not-allowed'
import { BriefServiceError, generateBrief } from '~/lib/interviews/brief-service'
import { requireTenantPrincipal, TenantAuthorizationError } from '~/shared/lib/auth/tenant-principal'
import { withTenantContext } from '~/shared/lib/db/tenant-context'
import { env } from '~/shared/lib/env'
import { generateBriefRequestSchema } from '~/shared/lib/interview-api'
import { deriveDocumentStatus } from '~/shared/lib/interviews'
import { findActiveBrief, findLatestBrief } from '~/shared/lib/repositories/interviews'
import { findSubmissionByInvitation } from '~/shared/lib/repositories/scheduling'
import { emitSecurityAudit } from '~/shared/lib/security/audit'
import { consoleSecurityAuditSink } from '~/shared/lib/security/audit-sink'
import { briefContextForEvent } from '~/lib/interviews/brief-context'
import { interviewIdGuard } from '~/shared/lib/api/interview-id'

/**
 * Read and generate the interview brief (plan:
 * calendar-scheduling-interview-intelligence, Phase 8).
 *
 * ## `interviewId` is the calendar event id
 *
 * An interview *is* a calendar event in this schema — `interview_briefs.event_id` points at
 * `calendar_events` — so the path parameter is that id. `interview_sessions` does not exist until
 * Phase 9 and would add nothing here: the brief is prepared before any session begins.
 *
 * ## Authorization is RLS, not a check in this handler
 *
 * `withTenantContext` pins `app.organization_id` and `app.user_id`, and `interview_briefs`' policies do
 * the rest: the owner, or a colleague with `event_participants.material_access_granted = true`, and nobody else
 * — not even an organization admin. So "not yours" and "does not exist" produce the same empty read
 * here, which is the right answer for both: distinguishing them would tell a caller that an interview
 * exists and they cannot see it.
 *
 * ## Generation is explicit about cost
 *
 * `creditConfirmation: true` is required in the body. It is not security — a client can always send it —
 * but it means a brief is never generated by an accidental POST or a retried request the user did not
 * intend, and five credits are five credits.
 */
export const Route = createFileRoute('/api/interviews/$interviewId/brief/')({
  component: () => null,
  server: {
    handlers: {
      // Every other method answers 405, not a 200 HTML page. See http/method-not-allowed.ts.
      ANY: methodNotAllowed(['GET', 'POST']),

      GET: async ({ request, params }) => {
        const guard = interviewIdGuard(params.interviewId)
        if (guard) return guard
        try {
          const principal = await requireTenantPrincipal(request)
          const result = await withTenantContext(principal, async (transaction) => {
            /*
             * Authorize first. The queries below scope by `principal.organizationId`, so another
             * tenant found nothing and got `200 {brief: null}` — no data crossed, but the status told
             * a stranger the request was fine. The POST on this route already guarded; the GET did not.
             */
            const context = await briefContextForEvent(transaction, principal, params.interviewId)
            if (!context) return null
            const active = await findActiveBrief(transaction, {
              organizationId: principal.organizationId,
              eventId: params.interviewId,
            })
            const latest = await findLatestBrief(transaction, {
              organizationId: principal.organizationId,
              eventId: params.interviewId,
            })
            return { active, latest }
          })

          // No relationship to this interview is a 404, the same answer as one that does not exist.
          if (!result) return Response.json({ error: 'not_found' }, { status: 404 })
          // A relationship but no brief written yet is a legitimate empty answer.
          if (!result.latest) return Response.json({ brief: null, latestVersion: null }, { status: 200 })

          return Response.json({
            // The active version is what a reader should act on; the latest may be a draft awaiting
            // review. Both are returned because the editor needs to know a newer draft exists.
            brief: toBriefDto(result.active ?? result.latest),
            latestVersion: result.latest.version,
            hasUnreviewedDraft: result.latest.status === 'draft',
            // Answered by the server, so the client never has to infer it from a role string. A
            // participant reads a brief and must not be offered a regenerate button the API will refuse —
            // `ownerUserId` is stripped from the DTO precisely so this is the only thing that conveys it.
            canEdit: result.latest.ownerUserId === principal.userId,
          })
        } catch (error) {
          if (error instanceof TenantAuthorizationError) {
            return Response.json({ error: 'forbidden' }, { status: 403 })
          }
          console.error('interview brief read error:', (error as Error)?.name)
          return Response.json({ error: 'failed' }, { status: 500 })
        }
      },

      POST: async ({ request, params }) => {
        const guard = interviewIdGuard(params.interviewId)
        if (guard) return guard
        try {
          if (env.SENSITIVE_AI_ENABLED !== 'true' && env.CANDIDATE_UPLOADS_ENABLED !== 'true') {
            // Both switches off means the feature is not deployed here at all. With only the AI switch
            // off the service still produces a deterministic fallback, which is useful, so that case
            // deliberately proceeds.
            return Response.json({ error: 'interviews_disabled' }, { status: 503 })
          }
          const principal = await requireTenantPrincipal(request)
          const parsed = generateBriefRequestSchema.safeParse(await request.json().catch(() => ({})))
          if (!parsed.success) {
            return Response.json({ error: 'invalid_input', details: parsed.error.flatten() }, { status: 400 })
          }

          const outcome = await withTenantContext(principal, async (transaction) => {
            const context = await briefContextForEvent(transaction, principal, params.interviewId)
            if (!context) return { kind: 'not_found' as const }

            const latest = await findLatestBrief(transaction, {
              organizationId: principal.organizationId,
              eventId: params.interviewId,
            })
            // Optimistic guard on the client's view. `0` means "there should be none yet", which is what
            // a first generation sends.
            if ((latest?.version ?? 0) !== parsed.data.expectedVersion) {
              return { kind: 'version_conflict' as const, latestVersion: latest?.version ?? 0 }
            }

            const submission = await findSubmissionByInvitation(
              transaction,
              principal.organizationId,
              context.invitationId,
            )
            if (!submission) return { kind: 'no_submission' as const }

            return {
              kind: 'ran' as const,
              result: await generateBrief(transaction, principal, {
                eventId: params.interviewId,
                submissionId: submission.id,
                roleTitle: context.roleTitle,
                roleContext: context.roleContext,
              }),
            }
          })

          if (outcome.kind === 'not_found') return Response.json({ error: 'not_found' }, { status: 404 })
          if (outcome.kind === 'no_submission') {
            return Response.json({ error: 'no_candidate_submission' }, { status: 409 })
          }
          if (outcome.kind === 'version_conflict') {
            return Response.json(
              { error: 'state_changed', latestVersion: outcome.latestVersion },
              { status: 409 },
            )
          }

          await emitSecurityAudit({
            organizationId: principal.organizationId,
            actorUserId: principal.userId,
            action: 'interview.brief.generate',
            targetType: 'calendar_event',
            targetId: params.interviewId,
            result: 'allowed',
            requestId: principal.requestId,
            // The outcome kind only. A brief's content is an assessment of a named person and has no
            // business in an audit line.
            details: { outcome: outcome.result.kind },
          }, consoleSecurityAuditSink)

          if (outcome.result.kind === 'no_evidence') {
            return Response.json({
              status: 'failed',
              reason: 'no_evidence',
              // The counts, so the UI can say what is still processing rather than just failing.
              evidence: outcome.result.summary,
            }, { status: 409 })
          }

          return Response.json({
            status: 'ready',
            version: outcome.result.brief.version,
            ...(outcome.result.kind === 'fallback' ? { fallbackReason: outcome.result.reason } : {}),
          })
        } catch (error) {
          if (error instanceof TenantAuthorizationError) {
            return Response.json({ error: 'forbidden' }, { status: 403 })
          }
          if (error instanceof BriefServiceError) {
            // 402 for credits so the client can route to the top-up flow rather than showing a generic
            // failure; 403 for a tier that does not include the feature at all.
            const status = error.code === 'insufficient_credits' ? 402 : error.code === 'version_conflict' ? 409 : 403
            return Response.json({ error: error.code }, { status })
          }
          console.error('interview brief generate error:', (error as Error)?.name)
          return Response.json({ error: 'failed' }, { status: 500 })
        }
      },
    },
  },
})

/**
 * The brief a client receives.
 *
 * Explicit field list rather than spreading the row: `ownerUserId` and `retentionExpiresAt` are internal,
 * and a spread would ship every column a future migration adds without anyone deciding to.
 */
export function toBriefDto(brief: {
  id: string
  eventId: string
  version: number
  status: string
  content: unknown
  evidenceManifest: unknown
  provider: string | null
  model: string | null
  promptVersion: string | null
  editedByUserId: string | null
}) {
  return {
    id: brief.id,
    eventId: brief.eventId,
    version: brief.version,
    status: brief.status,
    content: brief.content,
    evidenceManifest: brief.evidenceManifest,
    // Provenance is shown: a reader deciding how much weight to give a brief should know whether a
    // model wrote it, which one, and whether a human has since edited it.
    provider: brief.provider,
    model: brief.model,
    promptVersion: brief.promptVersion,
    editedByUserId: brief.editedByUserId,
  }
}

/** Re-exported so `$version.ts` shares one DTO shape rather than defining a second. */
export { deriveDocumentStatus }
