/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as ExploreIndexRouteImport } from './routes/explore/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding/welcome'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding/success'
import { Route as OnboardingSearchRouteImport } from './routes/onboarding/search'
import { Route as OnboardingSaveRouteImport } from './routes/onboarding/save'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalImprintRouteImport } from './routes/legal/imprint'
import { Route as LegalCookiesRouteImport } from './routes/legal/cookies'
import { Route as ChangelogSlugRouteImport } from './routes/changelog/$slug'
import { Route as BuildersBuilderIdRouteImport } from './routes/builders/$builderId'
import { Route as BlogAtomDotxmlRouteImport } from './routes/blog/atom[.]xml'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiStatusIndexRouteImport } from './routes/api/status/index'
import { Route as ApiRoadmapIndexRouteImport } from './routes/api/roadmap/index'
import { Route as ApiRecommendationsIndexRouteImport } from './routes/api/recommendations/index'
import { Route as ApiQueriesIndexRouteImport } from './routes/api/queries/index'
import { Route as ApiIncidentsIndexRouteImport } from './routes/api/incidents/index'
import { Route as ApiConsentIndexRouteImport } from './routes/api/consent/index'
import { Route as ApiChangelogIndexRouteImport } from './routes/api/changelog/index'
import { Route as DashboardSearchIndexRouteImport } from './routes/_dashboard/search/index'
import { Route as DashboardMeIndexRouteImport } from './routes/_dashboard/me/index'
import { Route as DashboardExportsIndexRouteImport } from './routes/_dashboard/exports/index'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as ApiSearchBuildersRouteImport } from './routes/api/search/builders'
import { Route as ApiOnboardingStatusRouteImport } from './routes/api/onboarding/status'
import { Route as ApiOnboardingSkipRouteImport } from './routes/api/onboarding/skip'
import { Route as ApiOnboardingCompleteRouteImport } from './routes/api/onboarding/complete'
import { Route as ApiOgExploreRouteImport } from './routes/api/og/explore'
import { Route as ApiFeedsSearchIdRouteImport } from './routes/api/feeds/$searchId'
import { Route as ApiExportBuildersRouteImport } from './routes/api/export/builders'
import { Route as ApiDashboardStatsRouteImport } from './routes/api/dashboard/stats'
import { Route as ApiChangelogSlugRouteImport } from './routes/api/changelog/$slug'
import { Route as ApiBuildersBuilderIdRouteImport } from './routes/api/builders/$builderId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardSettingsPrivacyRouteImport } from './routes/_dashboard/settings/privacy'
import { Route as DashboardAdminRoadmapRouteImport } from './routes/_dashboard/admin/roadmap'
import { Route as DashboardAdminIncidentsRouteImport } from './routes/_dashboard/admin/incidents'
import { Route as DashboardAdminChangelogRouteImport } from './routes/_dashboard/admin/changelog'
import { Route as ApiMeDeleteAccountIndexRouteImport } from './routes/api/me/delete-account/index'
import { Route as ApiMeDataExportIndexRouteImport } from './routes/api/me/data-export/index'
import { Route as ApiMeBuilderIndexRouteImport } from './routes/api/me/builder/index'
import { Route as ApiBuildersRecentIndexRouteImport } from './routes/api/builders/recent/index'
import { Route as ApiAdminRoadmapIndexRouteImport } from './routes/api/admin/roadmap/index'
import { Route as ApiAdminIncidentsIndexRouteImport } from './routes/api/admin/incidents/index'
import { Route as ApiAdminChangelogIndexRouteImport } from './routes/api/admin/changelog/index'
import { Route as DashboardBuilderBuilderIdIndexRouteImport } from './routes/_dashboard/builder/$builderId/index'
import { Route as ApiMeDataExportIdRouteImport } from './routes/api/me/data-export/$id'
import { Route as ApiMeBuilderBuilderIdRouteImport } from './routes/api/me/builder/$builderId'
import { Route as ApiBuildersClaimVerifyRouteImport } from './routes/api/builders/claim/verify'
import { Route as ApiBuildersBuilderIdNotesRouteImport } from './routes/api/builders/$builderId/notes'
import { Route as ApiBuildersBuilderIdClaimRouteImport } from './routes/api/builders/$builderId/claim'
import { Route as ApiAdminRoadmapIdRouteImport } from './routes/api/admin/roadmap/$id'
import { Route as ApiAdminIncidentsIdRouteImport } from './routes/api/admin/incidents/$id'
import { Route as ApiAdminChangelogIdRouteImport } from './routes/api/admin/changelog/$id'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreIndexRoute = ExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChangelogRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/onboarding/welcome',
  path: '/onboarding/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/onboarding/success',
  path: '/onboarding/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSearchRoute = OnboardingSearchRouteImport.update({
  id: '/onboarding/search',
  path: '/onboarding/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSaveRoute = OnboardingSaveRouteImport.update({
  id: '/onboarding/save',
  path: '/onboarding/save',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalImprintRoute = LegalImprintRouteImport.update({
  id: '/legal/imprint',
  path: '/legal/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogSlugRoute = ChangelogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ChangelogRoute,
} as any)
const BuildersBuilderIdRoute = BuildersBuilderIdRouteImport.update({
  id: '/builders/$builderId',
  path: '/builders/$builderId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAtomDotxmlRoute = BlogAtomDotxmlRouteImport.update({
  id: '/blog/atom.xml',
  path: '/blog/atom.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusIndexRoute = ApiStatusIndexRouteImport.update({
  id: '/api/status/',
  path: '/api/status/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoadmapIndexRoute = ApiRoadmapIndexRouteImport.update({
  id: '/api/roadmap/',
  path: '/api/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecommendationsIndexRoute = ApiRecommendationsIndexRouteImport.update({
  id: '/api/recommendations/',
  path: '/api/recommendations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueriesIndexRoute = ApiQueriesIndexRouteImport.update({
  id: '/api/queries/',
  path: '/api/queries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIncidentsIndexRoute = ApiIncidentsIndexRouteImport.update({
  id: '/api/incidents/',
  path: '/api/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsentIndexRoute = ApiConsentIndexRouteImport.update({
  id: '/api/consent/',
  path: '/api/consent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChangelogIndexRoute = ApiChangelogIndexRouteImport.update({
  id: '/api/changelog/',
  path: '/api/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSearchIndexRoute = DashboardSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMeIndexRoute = DashboardMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExportsIndexRoute = DashboardExportsIndexRouteImport.update({
  id: '/exports/',
  path: '/exports/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiSearchBuildersRoute = ApiSearchBuildersRouteImport.update({
  id: '/api/search/builders',
  path: '/api/search/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingStatusRoute = ApiOnboardingStatusRouteImport.update({
  id: '/api/onboarding/status',
  path: '/api/onboarding/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingSkipRoute = ApiOnboardingSkipRouteImport.update({
  id: '/api/onboarding/skip',
  path: '/api/onboarding/skip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingCompleteRoute = ApiOnboardingCompleteRouteImport.update({
  id: '/api/onboarding/complete',
  path: '/api/onboarding/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgExploreRoute = ApiOgExploreRouteImport.update({
  id: '/api/og/explore',
  path: '/api/og/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedsSearchIdRoute = ApiFeedsSearchIdRouteImport.update({
  id: '/api/feeds/$searchId',
  path: '/api/feeds/$searchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportBuildersRoute = ApiExportBuildersRouteImport.update({
  id: '/api/export/builders',
  path: '/api/export/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardStatsRoute = ApiDashboardStatsRouteImport.update({
  id: '/api/dashboard/stats',
  path: '/api/dashboard/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChangelogSlugRoute = ApiChangelogSlugRouteImport.update({
  id: '/api/changelog/$slug',
  path: '/api/changelog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildersBuilderIdRoute = ApiBuildersBuilderIdRouteImport.update({
  id: '/api/builders/$builderId',
  path: '/api/builders/$builderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsPrivacyRoute =
  DashboardSettingsPrivacyRouteImport.update({
    id: '/settings/privacy',
    path: '/settings/privacy',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAdminRoadmapRoute = DashboardAdminRoadmapRouteImport.update({
  id: '/admin/roadmap',
  path: '/admin/roadmap',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminIncidentsRoute = DashboardAdminIncidentsRouteImport.update({
  id: '/admin/incidents',
  path: '/admin/incidents',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminChangelogRoute = DashboardAdminChangelogRouteImport.update({
  id: '/admin/changelog',
  path: '/admin/changelog',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiMeDeleteAccountIndexRoute = ApiMeDeleteAccountIndexRouteImport.update({
  id: '/api/me/delete-account/',
  path: '/api/me/delete-account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeDataExportIndexRoute = ApiMeDataExportIndexRouteImport.update({
  id: '/api/me/data-export/',
  path: '/api/me/data-export/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeBuilderIndexRoute = ApiMeBuilderIndexRouteImport.update({
  id: '/api/me/builder/',
  path: '/api/me/builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildersRecentIndexRoute = ApiBuildersRecentIndexRouteImport.update({
  id: '/api/builders/recent/',
  path: '/api/builders/recent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoadmapIndexRoute = ApiAdminRoadmapIndexRouteImport.update({
  id: '/api/admin/roadmap/',
  path: '/api/admin/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIncidentsIndexRoute = ApiAdminIncidentsIndexRouteImport.update({
  id: '/api/admin/incidents/',
  path: '/api/admin/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminChangelogIndexRoute = ApiAdminChangelogIndexRouteImport.update({
  id: '/api/admin/changelog/',
  path: '/api/admin/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuilderBuilderIdIndexRoute =
  DashboardBuilderBuilderIdIndexRouteImport.update({
    id: '/builder/$builderId/',
    path: '/builder/$builderId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiMeDataExportIdRoute = ApiMeDataExportIdRouteImport.update({
  id: '/api/me/data-export/$id',
  path: '/api/me/data-export/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeBuilderBuilderIdRoute = ApiMeBuilderBuilderIdRouteImport.update({
  id: '/api/me/builder/$builderId',
  path: '/api/me/builder/$builderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildersClaimVerifyRoute = ApiBuildersClaimVerifyRouteImport.update({
  id: '/api/builders/claim/verify',
  path: '/api/builders/claim/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildersBuilderIdNotesRoute =
  ApiBuildersBuilderIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => ApiBuildersBuilderIdRoute,
  } as any)
const ApiBuildersBuilderIdClaimRoute =
  ApiBuildersBuilderIdClaimRouteImport.update({
    id: '/claim',
    path: '/claim',
    getParentRoute: () => ApiBuildersBuilderIdRoute,
  } as any)
const ApiAdminRoadmapIdRoute = ApiAdminRoadmapIdRouteImport.update({
  id: '/api/admin/roadmap/$id',
  path: '/api/admin/roadmap/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIncidentsIdRoute = ApiAdminIncidentsIdRouteImport.update({
  id: '/api/admin/incidents/$id',
  path: '/api/admin/incidents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminChangelogIdRoute = ApiAdminChangelogIdRouteImport.update({
  id: '/api/admin/changelog/$id',
  path: '/api/admin/changelog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/changelog': typeof ChangelogRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/atom.xml': typeof BlogAtomDotxmlRoute
  '/builders/$builderId': typeof BuildersBuilderIdRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/onboarding/save': typeof OnboardingSaveRoute
  '/onboarding/search': typeof OnboardingSearchRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/blog/': typeof BlogIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/admin/changelog': typeof DashboardAdminChangelogRoute
  '/admin/incidents': typeof DashboardAdminIncidentsRoute
  '/admin/roadmap': typeof DashboardAdminRoadmapRoute
  '/settings/privacy': typeof DashboardSettingsPrivacyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builders/$builderId': typeof ApiBuildersBuilderIdRouteWithChildren
  '/api/changelog/$slug': typeof ApiChangelogSlugRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/export/builders': typeof ApiExportBuildersRoute
  '/api/feeds/$searchId': typeof ApiFeedsSearchIdRoute
  '/api/og/explore': typeof ApiOgExploreRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/skip': typeof ApiOnboardingSkipRoute
  '/api/onboarding/status': typeof ApiOnboardingStatusRoute
  '/api/search/builders': typeof ApiSearchBuildersRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/exports/': typeof DashboardExportsIndexRoute
  '/me/': typeof DashboardMeIndexRoute
  '/search/': typeof DashboardSearchIndexRoute
  '/api/changelog/': typeof ApiChangelogIndexRoute
  '/api/consent/': typeof ApiConsentIndexRoute
  '/api/incidents/': typeof ApiIncidentsIndexRoute
  '/api/queries/': typeof ApiQueriesIndexRoute
  '/api/recommendations/': typeof ApiRecommendationsIndexRoute
  '/api/roadmap/': typeof ApiRoadmapIndexRoute
  '/api/status/': typeof ApiStatusIndexRoute
  '/api/admin/changelog/$id': typeof ApiAdminChangelogIdRoute
  '/api/admin/incidents/$id': typeof ApiAdminIncidentsIdRoute
  '/api/admin/roadmap/$id': typeof ApiAdminRoadmapIdRoute
  '/api/builders/$builderId/claim': typeof ApiBuildersBuilderIdClaimRoute
  '/api/builders/$builderId/notes': typeof ApiBuildersBuilderIdNotesRoute
  '/api/builders/claim/verify': typeof ApiBuildersClaimVerifyRoute
  '/api/me/builder/$builderId': typeof ApiMeBuilderBuilderIdRoute
  '/api/me/data-export/$id': typeof ApiMeDataExportIdRoute
  '/builder/$builderId/': typeof DashboardBuilderBuilderIdIndexRoute
  '/api/admin/changelog/': typeof ApiAdminChangelogIndexRoute
  '/api/admin/incidents/': typeof ApiAdminIncidentsIndexRoute
  '/api/admin/roadmap/': typeof ApiAdminRoadmapIndexRoute
  '/api/builders/recent/': typeof ApiBuildersRecentIndexRoute
  '/api/me/builder/': typeof ApiMeBuilderIndexRoute
  '/api/me/data-export/': typeof ApiMeDataExportIndexRoute
  '/api/me/delete-account/': typeof ApiMeDeleteAccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/atom.xml': typeof BlogAtomDotxmlRoute
  '/builders/$builderId': typeof BuildersBuilderIdRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/onboarding/save': typeof OnboardingSaveRoute
  '/onboarding/search': typeof OnboardingSearchRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/blog': typeof BlogIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/explore': typeof ExploreIndexRoute
  '/admin/changelog': typeof DashboardAdminChangelogRoute
  '/admin/incidents': typeof DashboardAdminIncidentsRoute
  '/admin/roadmap': typeof DashboardAdminRoadmapRoute
  '/settings/privacy': typeof DashboardSettingsPrivacyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builders/$builderId': typeof ApiBuildersBuilderIdRouteWithChildren
  '/api/changelog/$slug': typeof ApiChangelogSlugRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/export/builders': typeof ApiExportBuildersRoute
  '/api/feeds/$searchId': typeof ApiFeedsSearchIdRoute
  '/api/og/explore': typeof ApiOgExploreRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/skip': typeof ApiOnboardingSkipRoute
  '/api/onboarding/status': typeof ApiOnboardingStatusRoute
  '/api/search/builders': typeof ApiSearchBuildersRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/exports': typeof DashboardExportsIndexRoute
  '/me': typeof DashboardMeIndexRoute
  '/search': typeof DashboardSearchIndexRoute
  '/api/changelog': typeof ApiChangelogIndexRoute
  '/api/consent': typeof ApiConsentIndexRoute
  '/api/incidents': typeof ApiIncidentsIndexRoute
  '/api/queries': typeof ApiQueriesIndexRoute
  '/api/recommendations': typeof ApiRecommendationsIndexRoute
  '/api/roadmap': typeof ApiRoadmapIndexRoute
  '/api/status': typeof ApiStatusIndexRoute
  '/api/admin/changelog/$id': typeof ApiAdminChangelogIdRoute
  '/api/admin/incidents/$id': typeof ApiAdminIncidentsIdRoute
  '/api/admin/roadmap/$id': typeof ApiAdminRoadmapIdRoute
  '/api/builders/$builderId/claim': typeof ApiBuildersBuilderIdClaimRoute
  '/api/builders/$builderId/notes': typeof ApiBuildersBuilderIdNotesRoute
  '/api/builders/claim/verify': typeof ApiBuildersClaimVerifyRoute
  '/api/me/builder/$builderId': typeof ApiMeBuilderBuilderIdRoute
  '/api/me/data-export/$id': typeof ApiMeDataExportIdRoute
  '/builder/$builderId': typeof DashboardBuilderBuilderIdIndexRoute
  '/api/admin/changelog': typeof ApiAdminChangelogIndexRoute
  '/api/admin/incidents': typeof ApiAdminIncidentsIndexRoute
  '/api/admin/roadmap': typeof ApiAdminRoadmapIndexRoute
  '/api/builders/recent': typeof ApiBuildersRecentIndexRoute
  '/api/me/builder': typeof ApiMeBuilderIndexRoute
  '/api/me/data-export': typeof ApiMeDataExportIndexRoute
  '/api/me/delete-account': typeof ApiMeDeleteAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_landing': typeof LandingRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/changelog': typeof ChangelogRouteWithChildren
  '/roadmap': typeof RoadmapRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/atom.xml': typeof BlogAtomDotxmlRoute
  '/builders/$builderId': typeof BuildersBuilderIdRoute
  '/changelog/$slug': typeof ChangelogSlugRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/onboarding/save': typeof OnboardingSaveRoute
  '/onboarding/search': typeof OnboardingSearchRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/_landing/': typeof LandingIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/explore/': typeof ExploreIndexRoute
  '/_dashboard/admin/changelog': typeof DashboardAdminChangelogRoute
  '/_dashboard/admin/incidents': typeof DashboardAdminIncidentsRoute
  '/_dashboard/admin/roadmap': typeof DashboardAdminRoadmapRoute
  '/_dashboard/settings/privacy': typeof DashboardSettingsPrivacyRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builders/$builderId': typeof ApiBuildersBuilderIdRouteWithChildren
  '/api/changelog/$slug': typeof ApiChangelogSlugRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/export/builders': typeof ApiExportBuildersRoute
  '/api/feeds/$searchId': typeof ApiFeedsSearchIdRoute
  '/api/og/explore': typeof ApiOgExploreRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/skip': typeof ApiOnboardingSkipRoute
  '/api/onboarding/status': typeof ApiOnboardingStatusRoute
  '/api/search/builders': typeof ApiSearchBuildersRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/exports/': typeof DashboardExportsIndexRoute
  '/_dashboard/me/': typeof DashboardMeIndexRoute
  '/_dashboard/search/': typeof DashboardSearchIndexRoute
  '/api/changelog/': typeof ApiChangelogIndexRoute
  '/api/consent/': typeof ApiConsentIndexRoute
  '/api/incidents/': typeof ApiIncidentsIndexRoute
  '/api/queries/': typeof ApiQueriesIndexRoute
  '/api/recommendations/': typeof ApiRecommendationsIndexRoute
  '/api/roadmap/': typeof ApiRoadmapIndexRoute
  '/api/status/': typeof ApiStatusIndexRoute
  '/api/admin/changelog/$id': typeof ApiAdminChangelogIdRoute
  '/api/admin/incidents/$id': typeof ApiAdminIncidentsIdRoute
  '/api/admin/roadmap/$id': typeof ApiAdminRoadmapIdRoute
  '/api/builders/$builderId/claim': typeof ApiBuildersBuilderIdClaimRoute
  '/api/builders/$builderId/notes': typeof ApiBuildersBuilderIdNotesRoute
  '/api/builders/claim/verify': typeof ApiBuildersClaimVerifyRoute
  '/api/me/builder/$builderId': typeof ApiMeBuilderBuilderIdRoute
  '/api/me/data-export/$id': typeof ApiMeDataExportIdRoute
  '/_dashboard/builder/$builderId/': typeof DashboardBuilderBuilderIdIndexRoute
  '/api/admin/changelog/': typeof ApiAdminChangelogIndexRoute
  '/api/admin/incidents/': typeof ApiAdminIncidentsIndexRoute
  '/api/admin/roadmap/': typeof ApiAdminRoadmapIndexRoute
  '/api/builders/recent/': typeof ApiBuildersRecentIndexRoute
  '/api/me/builder/': typeof ApiMeBuilderIndexRoute
  '/api/me/data-export/': typeof ApiMeDataExportIndexRoute
  '/api/me/delete-account/': typeof ApiMeDeleteAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/changelog'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/status'
    | '/api/health'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/blog/$slug'
    | '/blog/atom.xml'
    | '/builders/$builderId'
    | '/changelog/$slug'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/onboarding/save'
    | '/onboarding/search'
    | '/onboarding/success'
    | '/onboarding/welcome'
    | '/blog/'
    | '/changelog/'
    | '/explore/'
    | '/admin/changelog'
    | '/admin/incidents'
    | '/admin/roadmap'
    | '/settings/privacy'
    | '/api/auth/$'
    | '/api/builders/$builderId'
    | '/api/changelog/$slug'
    | '/api/dashboard/stats'
    | '/api/export/builders'
    | '/api/feeds/$searchId'
    | '/api/og/explore'
    | '/api/onboarding/complete'
    | '/api/onboarding/skip'
    | '/api/onboarding/status'
    | '/api/search/builders'
    | '/dashboard/'
    | '/exports/'
    | '/me/'
    | '/search/'
    | '/api/changelog/'
    | '/api/consent/'
    | '/api/incidents/'
    | '/api/queries/'
    | '/api/recommendations/'
    | '/api/roadmap/'
    | '/api/status/'
    | '/api/admin/changelog/$id'
    | '/api/admin/incidents/$id'
    | '/api/admin/roadmap/$id'
    | '/api/builders/$builderId/claim'
    | '/api/builders/$builderId/notes'
    | '/api/builders/claim/verify'
    | '/api/me/builder/$builderId'
    | '/api/me/data-export/$id'
    | '/builder/$builderId/'
    | '/api/admin/changelog/'
    | '/api/admin/incidents/'
    | '/api/admin/roadmap/'
    | '/api/builders/recent/'
    | '/api/me/builder/'
    | '/api/me/data-export/'
    | '/api/me/delete-account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/status'
    | '/api/health'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/blog/$slug'
    | '/blog/atom.xml'
    | '/builders/$builderId'
    | '/changelog/$slug'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/onboarding/save'
    | '/onboarding/search'
    | '/onboarding/success'
    | '/onboarding/welcome'
    | '/blog'
    | '/changelog'
    | '/explore'
    | '/admin/changelog'
    | '/admin/incidents'
    | '/admin/roadmap'
    | '/settings/privacy'
    | '/api/auth/$'
    | '/api/builders/$builderId'
    | '/api/changelog/$slug'
    | '/api/dashboard/stats'
    | '/api/export/builders'
    | '/api/feeds/$searchId'
    | '/api/og/explore'
    | '/api/onboarding/complete'
    | '/api/onboarding/skip'
    | '/api/onboarding/status'
    | '/api/search/builders'
    | '/dashboard'
    | '/exports'
    | '/me'
    | '/search'
    | '/api/changelog'
    | '/api/consent'
    | '/api/incidents'
    | '/api/queries'
    | '/api/recommendations'
    | '/api/roadmap'
    | '/api/status'
    | '/api/admin/changelog/$id'
    | '/api/admin/incidents/$id'
    | '/api/admin/roadmap/$id'
    | '/api/builders/$builderId/claim'
    | '/api/builders/$builderId/notes'
    | '/api/builders/claim/verify'
    | '/api/me/builder/$builderId'
    | '/api/me/data-export/$id'
    | '/builder/$builderId'
    | '/api/admin/changelog'
    | '/api/admin/incidents'
    | '/api/admin/roadmap'
    | '/api/builders/recent'
    | '/api/me/builder'
    | '/api/me/data-export'
    | '/api/me/delete-account'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_landing'
    | '/auth'
    | '/changelog'
    | '/roadmap'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/status'
    | '/api/health'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/blog/$slug'
    | '/blog/atom.xml'
    | '/builders/$builderId'
    | '/changelog/$slug'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/onboarding/save'
    | '/onboarding/search'
    | '/onboarding/success'
    | '/onboarding/welcome'
    | '/_landing/'
    | '/blog/'
    | '/changelog/'
    | '/explore/'
    | '/_dashboard/admin/changelog'
    | '/_dashboard/admin/incidents'
    | '/_dashboard/admin/roadmap'
    | '/_dashboard/settings/privacy'
    | '/api/auth/$'
    | '/api/builders/$builderId'
    | '/api/changelog/$slug'
    | '/api/dashboard/stats'
    | '/api/export/builders'
    | '/api/feeds/$searchId'
    | '/api/og/explore'
    | '/api/onboarding/complete'
    | '/api/onboarding/skip'
    | '/api/onboarding/status'
    | '/api/search/builders'
    | '/_dashboard/dashboard/'
    | '/_dashboard/exports/'
    | '/_dashboard/me/'
    | '/_dashboard/search/'
    | '/api/changelog/'
    | '/api/consent/'
    | '/api/incidents/'
    | '/api/queries/'
    | '/api/recommendations/'
    | '/api/roadmap/'
    | '/api/status/'
    | '/api/admin/changelog/$id'
    | '/api/admin/incidents/$id'
    | '/api/admin/roadmap/$id'
    | '/api/builders/$builderId/claim'
    | '/api/builders/$builderId/notes'
    | '/api/builders/claim/verify'
    | '/api/me/builder/$builderId'
    | '/api/me/data-export/$id'
    | '/_dashboard/builder/$builderId/'
    | '/api/admin/changelog/'
    | '/api/admin/incidents/'
    | '/api/admin/roadmap/'
    | '/api/builders/recent/'
    | '/api/me/builder/'
    | '/api/me/data-export/'
    | '/api/me/delete-account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ChangelogRoute: typeof ChangelogRouteWithChildren
  RoadmapRoute: typeof RoadmapRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogAtomDotxmlRoute: typeof BlogAtomDotxmlRoute
  BuildersBuilderIdRoute: typeof BuildersBuilderIdRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalImprintRoute: typeof LegalImprintRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  OnboardingSaveRoute: typeof OnboardingSaveRoute
  OnboardingSearchRoute: typeof OnboardingSearchRoute
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ExploreIndexRoute: typeof ExploreIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBuildersBuilderIdRoute: typeof ApiBuildersBuilderIdRouteWithChildren
  ApiChangelogSlugRoute: typeof ApiChangelogSlugRoute
  ApiDashboardStatsRoute: typeof ApiDashboardStatsRoute
  ApiExportBuildersRoute: typeof ApiExportBuildersRoute
  ApiFeedsSearchIdRoute: typeof ApiFeedsSearchIdRoute
  ApiOgExploreRoute: typeof ApiOgExploreRoute
  ApiOnboardingCompleteRoute: typeof ApiOnboardingCompleteRoute
  ApiOnboardingSkipRoute: typeof ApiOnboardingSkipRoute
  ApiOnboardingStatusRoute: typeof ApiOnboardingStatusRoute
  ApiSearchBuildersRoute: typeof ApiSearchBuildersRoute
  ApiChangelogIndexRoute: typeof ApiChangelogIndexRoute
  ApiConsentIndexRoute: typeof ApiConsentIndexRoute
  ApiIncidentsIndexRoute: typeof ApiIncidentsIndexRoute
  ApiQueriesIndexRoute: typeof ApiQueriesIndexRoute
  ApiRecommendationsIndexRoute: typeof ApiRecommendationsIndexRoute
  ApiRoadmapIndexRoute: typeof ApiRoadmapIndexRoute
  ApiStatusIndexRoute: typeof ApiStatusIndexRoute
  ApiAdminChangelogIdRoute: typeof ApiAdminChangelogIdRoute
  ApiAdminIncidentsIdRoute: typeof ApiAdminIncidentsIdRoute
  ApiAdminRoadmapIdRoute: typeof ApiAdminRoadmapIdRoute
  ApiBuildersClaimVerifyRoute: typeof ApiBuildersClaimVerifyRoute
  ApiMeBuilderBuilderIdRoute: typeof ApiMeBuilderBuilderIdRoute
  ApiMeDataExportIdRoute: typeof ApiMeDataExportIdRoute
  ApiAdminChangelogIndexRoute: typeof ApiAdminChangelogIndexRoute
  ApiAdminIncidentsIndexRoute: typeof ApiAdminIncidentsIndexRoute
  ApiAdminRoadmapIndexRoute: typeof ApiAdminRoadmapIndexRoute
  ApiBuildersRecentIndexRoute: typeof ApiBuildersRecentIndexRoute
  ApiMeBuilderIndexRoute: typeof ApiMeBuilderIndexRoute
  ApiMeDataExportIndexRoute: typeof ApiMeDataExportIndexRoute
  ApiMeDeleteAccountIndexRoute: typeof ApiMeDeleteAccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/': {
      id: '/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/success': {
      id: '/onboarding/success'
      path: '/onboarding/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/search': {
      id: '/onboarding/search'
      path: '/onboarding/search'
      fullPath: '/onboarding/search'
      preLoaderRoute: typeof OnboardingSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/save': {
      id: '/onboarding/save'
      path: '/onboarding/save'
      fullPath: '/onboarding/save'
      preLoaderRoute: typeof OnboardingSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/imprint': {
      id: '/legal/imprint'
      path: '/legal/imprint'
      fullPath: '/legal/imprint'
      preLoaderRoute: typeof LegalImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/$slug': {
      id: '/changelog/$slug'
      path: '/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof ChangelogSlugRouteImport
      parentRoute: typeof ChangelogRoute
    }
    '/builders/$builderId': {
      id: '/builders/$builderId'
      path: '/builders/$builderId'
      fullPath: '/builders/$builderId'
      preLoaderRoute: typeof BuildersBuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/atom.xml': {
      id: '/blog/atom.xml'
      path: '/blog/atom.xml'
      fullPath: '/blog/atom.xml'
      preLoaderRoute: typeof BlogAtomDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status/': {
      id: '/api/status/'
      path: '/api/status'
      fullPath: '/api/status/'
      preLoaderRoute: typeof ApiStatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roadmap/': {
      id: '/api/roadmap/'
      path: '/api/roadmap'
      fullPath: '/api/roadmap/'
      preLoaderRoute: typeof ApiRoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recommendations/': {
      id: '/api/recommendations/'
      path: '/api/recommendations'
      fullPath: '/api/recommendations/'
      preLoaderRoute: typeof ApiRecommendationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queries/': {
      id: '/api/queries/'
      path: '/api/queries'
      fullPath: '/api/queries/'
      preLoaderRoute: typeof ApiQueriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/incidents/': {
      id: '/api/incidents/'
      path: '/api/incidents'
      fullPath: '/api/incidents/'
      preLoaderRoute: typeof ApiIncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consent/': {
      id: '/api/consent/'
      path: '/api/consent'
      fullPath: '/api/consent/'
      preLoaderRoute: typeof ApiConsentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/changelog/': {
      id: '/api/changelog/'
      path: '/api/changelog'
      fullPath: '/api/changelog/'
      preLoaderRoute: typeof ApiChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/search/': {
      id: '/_dashboard/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof DashboardSearchIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/me/': {
      id: '/_dashboard/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof DashboardMeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/exports/': {
      id: '/_dashboard/exports/'
      path: '/exports'
      fullPath: '/exports/'
      preLoaderRoute: typeof DashboardExportsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/search/builders': {
      id: '/api/search/builders'
      path: '/api/search/builders'
      fullPath: '/api/search/builders'
      preLoaderRoute: typeof ApiSearchBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/status': {
      id: '/api/onboarding/status'
      path: '/api/onboarding/status'
      fullPath: '/api/onboarding/status'
      preLoaderRoute: typeof ApiOnboardingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/skip': {
      id: '/api/onboarding/skip'
      path: '/api/onboarding/skip'
      fullPath: '/api/onboarding/skip'
      preLoaderRoute: typeof ApiOnboardingSkipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/complete': {
      id: '/api/onboarding/complete'
      path: '/api/onboarding/complete'
      fullPath: '/api/onboarding/complete'
      preLoaderRoute: typeof ApiOnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/explore': {
      id: '/api/og/explore'
      path: '/api/og/explore'
      fullPath: '/api/og/explore'
      preLoaderRoute: typeof ApiOgExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feeds/$searchId': {
      id: '/api/feeds/$searchId'
      path: '/api/feeds/$searchId'
      fullPath: '/api/feeds/$searchId'
      preLoaderRoute: typeof ApiFeedsSearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/builders': {
      id: '/api/export/builders'
      path: '/api/export/builders'
      fullPath: '/api/export/builders'
      preLoaderRoute: typeof ApiExportBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/stats': {
      id: '/api/dashboard/stats'
      path: '/api/dashboard/stats'
      fullPath: '/api/dashboard/stats'
      preLoaderRoute: typeof ApiDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/changelog/$slug': {
      id: '/api/changelog/$slug'
      path: '/api/changelog/$slug'
      fullPath: '/api/changelog/$slug'
      preLoaderRoute: typeof ApiChangelogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builders/$builderId': {
      id: '/api/builders/$builderId'
      path: '/api/builders/$builderId'
      fullPath: '/api/builders/$builderId'
      preLoaderRoute: typeof ApiBuildersBuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/settings/privacy': {
      id: '/_dashboard/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof DashboardSettingsPrivacyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/admin/roadmap': {
      id: '/_dashboard/admin/roadmap'
      path: '/admin/roadmap'
      fullPath: '/admin/roadmap'
      preLoaderRoute: typeof DashboardAdminRoadmapRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/admin/incidents': {
      id: '/_dashboard/admin/incidents'
      path: '/admin/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof DashboardAdminIncidentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/admin/changelog': {
      id: '/_dashboard/admin/changelog'
      path: '/admin/changelog'
      fullPath: '/admin/changelog'
      preLoaderRoute: typeof DashboardAdminChangelogRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/me/delete-account/': {
      id: '/api/me/delete-account/'
      path: '/api/me/delete-account'
      fullPath: '/api/me/delete-account/'
      preLoaderRoute: typeof ApiMeDeleteAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/data-export/': {
      id: '/api/me/data-export/'
      path: '/api/me/data-export'
      fullPath: '/api/me/data-export/'
      preLoaderRoute: typeof ApiMeDataExportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/builder/': {
      id: '/api/me/builder/'
      path: '/api/me/builder'
      fullPath: '/api/me/builder/'
      preLoaderRoute: typeof ApiMeBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builders/recent/': {
      id: '/api/builders/recent/'
      path: '/api/builders/recent'
      fullPath: '/api/builders/recent/'
      preLoaderRoute: typeof ApiBuildersRecentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/roadmap/': {
      id: '/api/admin/roadmap/'
      path: '/api/admin/roadmap'
      fullPath: '/api/admin/roadmap/'
      preLoaderRoute: typeof ApiAdminRoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/incidents/': {
      id: '/api/admin/incidents/'
      path: '/api/admin/incidents'
      fullPath: '/api/admin/incidents/'
      preLoaderRoute: typeof ApiAdminIncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/changelog/': {
      id: '/api/admin/changelog/'
      path: '/api/admin/changelog'
      fullPath: '/api/admin/changelog/'
      preLoaderRoute: typeof ApiAdminChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/builder/$builderId/': {
      id: '/_dashboard/builder/$builderId/'
      path: '/builder/$builderId'
      fullPath: '/builder/$builderId/'
      preLoaderRoute: typeof DashboardBuilderBuilderIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/me/data-export/$id': {
      id: '/api/me/data-export/$id'
      path: '/api/me/data-export/$id'
      fullPath: '/api/me/data-export/$id'
      preLoaderRoute: typeof ApiMeDataExportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/builder/$builderId': {
      id: '/api/me/builder/$builderId'
      path: '/api/me/builder/$builderId'
      fullPath: '/api/me/builder/$builderId'
      preLoaderRoute: typeof ApiMeBuilderBuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builders/claim/verify': {
      id: '/api/builders/claim/verify'
      path: '/api/builders/claim/verify'
      fullPath: '/api/builders/claim/verify'
      preLoaderRoute: typeof ApiBuildersClaimVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builders/$builderId/notes': {
      id: '/api/builders/$builderId/notes'
      path: '/notes'
      fullPath: '/api/builders/$builderId/notes'
      preLoaderRoute: typeof ApiBuildersBuilderIdNotesRouteImport
      parentRoute: typeof ApiBuildersBuilderIdRoute
    }
    '/api/builders/$builderId/claim': {
      id: '/api/builders/$builderId/claim'
      path: '/claim'
      fullPath: '/api/builders/$builderId/claim'
      preLoaderRoute: typeof ApiBuildersBuilderIdClaimRouteImport
      parentRoute: typeof ApiBuildersBuilderIdRoute
    }
    '/api/admin/roadmap/$id': {
      id: '/api/admin/roadmap/$id'
      path: '/api/admin/roadmap/$id'
      fullPath: '/api/admin/roadmap/$id'
      preLoaderRoute: typeof ApiAdminRoadmapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/incidents/$id': {
      id: '/api/admin/incidents/$id'
      path: '/api/admin/incidents/$id'
      fullPath: '/api/admin/incidents/$id'
      preLoaderRoute: typeof ApiAdminIncidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/changelog/$id': {
      id: '/api/admin/changelog/$id'
      path: '/api/admin/changelog/$id'
      fullPath: '/api/admin/changelog/$id'
      preLoaderRoute: typeof ApiAdminChangelogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAdminChangelogRoute: typeof DashboardAdminChangelogRoute
  DashboardAdminIncidentsRoute: typeof DashboardAdminIncidentsRoute
  DashboardAdminRoadmapRoute: typeof DashboardAdminRoadmapRoute
  DashboardSettingsPrivacyRoute: typeof DashboardSettingsPrivacyRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardExportsIndexRoute: typeof DashboardExportsIndexRoute
  DashboardMeIndexRoute: typeof DashboardMeIndexRoute
  DashboardSearchIndexRoute: typeof DashboardSearchIndexRoute
  DashboardBuilderBuilderIdIndexRoute: typeof DashboardBuilderBuilderIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminChangelogRoute: DashboardAdminChangelogRoute,
  DashboardAdminIncidentsRoute: DashboardAdminIncidentsRoute,
  DashboardAdminRoadmapRoute: DashboardAdminRoadmapRoute,
  DashboardSettingsPrivacyRoute: DashboardSettingsPrivacyRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardExportsIndexRoute: DashboardExportsIndexRoute,
  DashboardMeIndexRoute: DashboardMeIndexRoute,
  DashboardSearchIndexRoute: DashboardSearchIndexRoute,
  DashboardBuilderBuilderIdIndexRoute: DashboardBuilderBuilderIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LandingRouteRouteChildren {
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ChangelogRouteChildren {
  ChangelogSlugRoute: typeof ChangelogSlugRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
}

const ChangelogRouteChildren: ChangelogRouteChildren = {
  ChangelogSlugRoute: ChangelogSlugRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
}

const ChangelogRouteWithChildren = ChangelogRoute._addFileChildren(
  ChangelogRouteChildren,
)

interface ApiBuildersBuilderIdRouteChildren {
  ApiBuildersBuilderIdClaimRoute: typeof ApiBuildersBuilderIdClaimRoute
  ApiBuildersBuilderIdNotesRoute: typeof ApiBuildersBuilderIdNotesRoute
}

const ApiBuildersBuilderIdRouteChildren: ApiBuildersBuilderIdRouteChildren = {
  ApiBuildersBuilderIdClaimRoute: ApiBuildersBuilderIdClaimRoute,
  ApiBuildersBuilderIdNotesRoute: ApiBuildersBuilderIdNotesRoute,
}

const ApiBuildersBuilderIdRouteWithChildren =
  ApiBuildersBuilderIdRoute._addFileChildren(ApiBuildersBuilderIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LandingRouteRoute: LandingRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ChangelogRoute: ChangelogRouteWithChildren,
  RoadmapRoute: RoadmapRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  ApiHealthRoute: ApiHealthRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogAtomDotxmlRoute: BlogAtomDotxmlRoute,
  BuildersBuilderIdRoute: BuildersBuilderIdRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalImprintRoute: LegalImprintRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  OnboardingSaveRoute: OnboardingSaveRoute,
  OnboardingSearchRoute: OnboardingSearchRoute,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  BlogIndexRoute: BlogIndexRoute,
  ExploreIndexRoute: ExploreIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBuildersBuilderIdRoute: ApiBuildersBuilderIdRouteWithChildren,
  ApiChangelogSlugRoute: ApiChangelogSlugRoute,
  ApiDashboardStatsRoute: ApiDashboardStatsRoute,
  ApiExportBuildersRoute: ApiExportBuildersRoute,
  ApiFeedsSearchIdRoute: ApiFeedsSearchIdRoute,
  ApiOgExploreRoute: ApiOgExploreRoute,
  ApiOnboardingCompleteRoute: ApiOnboardingCompleteRoute,
  ApiOnboardingSkipRoute: ApiOnboardingSkipRoute,
  ApiOnboardingStatusRoute: ApiOnboardingStatusRoute,
  ApiSearchBuildersRoute: ApiSearchBuildersRoute,
  ApiChangelogIndexRoute: ApiChangelogIndexRoute,
  ApiConsentIndexRoute: ApiConsentIndexRoute,
  ApiIncidentsIndexRoute: ApiIncidentsIndexRoute,
  ApiQueriesIndexRoute: ApiQueriesIndexRoute,
  ApiRecommendationsIndexRoute: ApiRecommendationsIndexRoute,
  ApiRoadmapIndexRoute: ApiRoadmapIndexRoute,
  ApiStatusIndexRoute: ApiStatusIndexRoute,
  ApiAdminChangelogIdRoute: ApiAdminChangelogIdRoute,
  ApiAdminIncidentsIdRoute: ApiAdminIncidentsIdRoute,
  ApiAdminRoadmapIdRoute: ApiAdminRoadmapIdRoute,
  ApiBuildersClaimVerifyRoute: ApiBuildersClaimVerifyRoute,
  ApiMeBuilderBuilderIdRoute: ApiMeBuilderBuilderIdRoute,
  ApiMeDataExportIdRoute: ApiMeDataExportIdRoute,
  ApiAdminChangelogIndexRoute: ApiAdminChangelogIndexRoute,
  ApiAdminIncidentsIndexRoute: ApiAdminIncidentsIndexRoute,
  ApiAdminRoadmapIndexRoute: ApiAdminRoadmapIndexRoute,
  ApiBuildersRecentIndexRoute: ApiBuildersRecentIndexRoute,
  ApiMeBuilderIndexRoute: ApiMeBuilderIndexRoute,
  ApiMeDataExportIndexRoute: ApiMeDataExportIndexRoute,
  ApiMeDeleteAccountIndexRoute: ApiMeDeleteAccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
