/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ApiQueriesIndexRouteImport } from './routes/api/queries/index'
import { Route as DashboardSearchIndexRouteImport } from './routes/_dashboard/search/index'
import { Route as DashboardExportsIndexRouteImport } from './routes/_dashboard/exports/index'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as ApiSearchBuildersRouteImport } from './routes/api/search/builders'
import { Route as ApiExportBuildersRouteImport } from './routes/api/export/builders'
import { Route as ApiDashboardStatsRouteImport } from './routes/api/dashboard/stats'
import { Route as ApiBuildersBuilderIdRouteImport } from './routes/api/builders/$builderId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardBuilderBuilderIdIndexRouteImport } from './routes/_dashboard/builder/$builderId/index'
import { Route as ApiBuildersBuilderIdNotesRouteImport } from './routes/api/builders/$builderId/notes'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiQueriesIndexRoute = ApiQueriesIndexRouteImport.update({
  id: '/api/queries/',
  path: '/api/queries/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSearchIndexRoute = DashboardSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExportsIndexRoute = DashboardExportsIndexRouteImport.update({
  id: '/exports/',
  path: '/exports/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiSearchBuildersRoute = ApiSearchBuildersRouteImport.update({
  id: '/api/search/builders',
  path: '/api/search/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportBuildersRoute = ApiExportBuildersRouteImport.update({
  id: '/api/export/builders',
  path: '/api/export/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardStatsRoute = ApiDashboardStatsRouteImport.update({
  id: '/api/dashboard/stats',
  path: '/api/dashboard/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildersBuilderIdRoute = ApiBuildersBuilderIdRouteImport.update({
  id: '/api/builders/$builderId',
  path: '/api/builders/$builderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuilderBuilderIdIndexRoute =
  DashboardBuilderBuilderIdIndexRouteImport.update({
    id: '/builder/$builderId/',
    path: '/builder/$builderId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiBuildersBuilderIdNotesRoute =
  ApiBuildersBuilderIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => ApiBuildersBuilderIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builders/$builderId': typeof ApiBuildersBuilderIdRouteWithChildren
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/export/builders': typeof ApiExportBuildersRoute
  '/api/search/builders': typeof ApiSearchBuildersRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/exports/': typeof DashboardExportsIndexRoute
  '/search/': typeof DashboardSearchIndexRoute
  '/api/queries/': typeof ApiQueriesIndexRoute
  '/api/builders/$builderId/notes': typeof ApiBuildersBuilderIdNotesRoute
  '/builder/$builderId/': typeof DashboardBuilderBuilderIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builders/$builderId': typeof ApiBuildersBuilderIdRouteWithChildren
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/export/builders': typeof ApiExportBuildersRoute
  '/api/search/builders': typeof ApiSearchBuildersRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/exports': typeof DashboardExportsIndexRoute
  '/search': typeof DashboardSearchIndexRoute
  '/api/queries': typeof ApiQueriesIndexRoute
  '/api/builders/$builderId/notes': typeof ApiBuildersBuilderIdNotesRoute
  '/builder/$builderId': typeof DashboardBuilderBuilderIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_landing': typeof LandingRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_landing/': typeof LandingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builders/$builderId': typeof ApiBuildersBuilderIdRouteWithChildren
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/export/builders': typeof ApiExportBuildersRoute
  '/api/search/builders': typeof ApiSearchBuildersRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/exports/': typeof DashboardExportsIndexRoute
  '/_dashboard/search/': typeof DashboardSearchIndexRoute
  '/api/queries/': typeof ApiQueriesIndexRoute
  '/api/builders/$builderId/notes': typeof ApiBuildersBuilderIdNotesRoute
  '/_dashboard/builder/$builderId/': typeof DashboardBuilderBuilderIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/api/auth/$'
    | '/api/builders/$builderId'
    | '/api/dashboard/stats'
    | '/api/export/builders'
    | '/api/search/builders'
    | '/dashboard/'
    | '/exports/'
    | '/search/'
    | '/api/queries/'
    | '/api/builders/$builderId/notes'
    | '/builder/$builderId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/api/auth/$'
    | '/api/builders/$builderId'
    | '/api/dashboard/stats'
    | '/api/export/builders'
    | '/api/search/builders'
    | '/dashboard'
    | '/exports'
    | '/search'
    | '/api/queries'
    | '/api/builders/$builderId/notes'
    | '/builder/$builderId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_landing'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_landing/'
    | '/api/auth/$'
    | '/api/builders/$builderId'
    | '/api/dashboard/stats'
    | '/api/export/builders'
    | '/api/search/builders'
    | '/_dashboard/dashboard/'
    | '/_dashboard/exports/'
    | '/_dashboard/search/'
    | '/api/queries/'
    | '/api/builders/$builderId/notes'
    | '/_dashboard/builder/$builderId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBuildersBuilderIdRoute: typeof ApiBuildersBuilderIdRouteWithChildren
  ApiDashboardStatsRoute: typeof ApiDashboardStatsRoute
  ApiExportBuildersRoute: typeof ApiExportBuildersRoute
  ApiSearchBuildersRoute: typeof ApiSearchBuildersRoute
  ApiQueriesIndexRoute: typeof ApiQueriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/queries/': {
      id: '/api/queries/'
      path: '/api/queries'
      fullPath: '/api/queries/'
      preLoaderRoute: typeof ApiQueriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/search/': {
      id: '/_dashboard/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof DashboardSearchIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/exports/': {
      id: '/_dashboard/exports/'
      path: '/exports'
      fullPath: '/exports/'
      preLoaderRoute: typeof DashboardExportsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/search/builders': {
      id: '/api/search/builders'
      path: '/api/search/builders'
      fullPath: '/api/search/builders'
      preLoaderRoute: typeof ApiSearchBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/builders': {
      id: '/api/export/builders'
      path: '/api/export/builders'
      fullPath: '/api/export/builders'
      preLoaderRoute: typeof ApiExportBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/stats': {
      id: '/api/dashboard/stats'
      path: '/api/dashboard/stats'
      fullPath: '/api/dashboard/stats'
      preLoaderRoute: typeof ApiDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builders/$builderId': {
      id: '/api/builders/$builderId'
      path: '/api/builders/$builderId'
      fullPath: '/api/builders/$builderId'
      preLoaderRoute: typeof ApiBuildersBuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/builder/$builderId/': {
      id: '/_dashboard/builder/$builderId/'
      path: '/builder/$builderId'
      fullPath: '/builder/$builderId/'
      preLoaderRoute: typeof DashboardBuilderBuilderIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/builders/$builderId/notes': {
      id: '/api/builders/$builderId/notes'
      path: '/notes'
      fullPath: '/api/builders/$builderId/notes'
      preLoaderRoute: typeof ApiBuildersBuilderIdNotesRouteImport
      parentRoute: typeof ApiBuildersBuilderIdRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardExportsIndexRoute: typeof DashboardExportsIndexRoute
  DashboardSearchIndexRoute: typeof DashboardSearchIndexRoute
  DashboardBuilderBuilderIdIndexRoute: typeof DashboardBuilderBuilderIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardExportsIndexRoute: DashboardExportsIndexRoute,
  DashboardSearchIndexRoute: DashboardSearchIndexRoute,
  DashboardBuilderBuilderIdIndexRoute: DashboardBuilderBuilderIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LandingRouteRouteChildren {
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ApiBuildersBuilderIdRouteChildren {
  ApiBuildersBuilderIdNotesRoute: typeof ApiBuildersBuilderIdNotesRoute
}

const ApiBuildersBuilderIdRouteChildren: ApiBuildersBuilderIdRouteChildren = {
  ApiBuildersBuilderIdNotesRoute: ApiBuildersBuilderIdNotesRoute,
}

const ApiBuildersBuilderIdRouteWithChildren =
  ApiBuildersBuilderIdRoute._addFileChildren(ApiBuildersBuilderIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LandingRouteRoute: LandingRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBuildersBuilderIdRoute: ApiBuildersBuilderIdRouteWithChildren,
  ApiDashboardStatsRoute: ApiDashboardStatsRoute,
  ApiExportBuildersRoute: ApiExportBuildersRoute,
  ApiSearchBuildersRoute: ApiSearchBuildersRoute,
  ApiQueriesIndexRoute: ApiQueriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
