/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as LandingRouteRouteImport } from './routes/_landing/route'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding/welcome'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding/success'
import { Route as OnboardingSearchRouteImport } from './routes/onboarding/search'
import { Route as OnboardingSaveRouteImport } from './routes/onboarding/save'
import { Route as BuildersBuilderIdRouteImport } from './routes/builders/$builderId'
import { Route as BlogAtomDotxmlRouteImport } from './routes/blog/atom[.]xml'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetRouteImport } from './routes/auth/reset'
import { Route as AuthForgotRouteImport } from './routes/auth/forgot'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as LandingStatusRouteImport } from './routes/_landing/status'
import { Route as LandingRoadmapRouteImport } from './routes/_landing/roadmap'
import { Route as LandingPricingRouteImport } from './routes/_landing/pricing'
import { Route as LandingChangelogRouteImport } from './routes/_landing/changelog'
import { Route as DashboardAlertsRouteImport } from './routes/_dashboard/alerts'
import { Route as ApiStatusIndexRouteImport } from './routes/api/status/index'
import { Route as ApiRoadmapIndexRouteImport } from './routes/api/roadmap/index'
import { Route as ApiRecommendationsIndexRouteImport } from './routes/api/recommendations/index'
import { Route as ApiQueriesIndexRouteImport } from './routes/api/queries/index'
import { Route as ApiIncidentsIndexRouteImport } from './routes/api/incidents/index'
import { Route as ApiConsentIndexRouteImport } from './routes/api/consent/index'
import { Route as ApiChangelogIndexRouteImport } from './routes/api/changelog/index'
import { Route as ApiAlertsIndexRouteImport } from './routes/api/alerts/index'
import { Route as LandingExploreIndexRouteImport } from './routes/_landing/explore/index'
import { Route as LandingChangelogIndexRouteImport } from './routes/_landing/changelog/index'
import { Route as LandingBlogIndexRouteImport } from './routes/_landing/blog/index'
import { Route as DashboardSearchIndexRouteImport } from './routes/_dashboard/search/index'
import { Route as DashboardMeIndexRouteImport } from './routes/_dashboard/me/index'
import { Route as DashboardExportsIndexRouteImport } from './routes/_dashboard/exports/index'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as ApiSearchBuildersRouteImport } from './routes/api/search/builders'
import { Route as ApiPlansRequestUpgradeRouteImport } from './routes/api/plans/request-upgrade'
import { Route as ApiPlansMeRouteImport } from './routes/api/plans/me'
import { Route as ApiOnboardingStatusRouteImport } from './routes/api/onboarding/status'
import { Route as ApiOnboardingSkipRouteImport } from './routes/api/onboarding/skip'
import { Route as ApiOnboardingCompleteRouteImport } from './routes/api/onboarding/complete'
import { Route as ApiOgExploreRouteImport } from './routes/api/og/explore'
import { Route as ApiFeedsSearchIdRouteImport } from './routes/api/feeds/$searchId'
import { Route as ApiExportBuildersRouteImport } from './routes/api/export/builders'
import { Route as ApiDashboardStatsRouteImport } from './routes/api/dashboard/stats'
import { Route as ApiChangelogSlugRouteImport } from './routes/api/changelog/$slug'
import { Route as ApiBuildersTrackRouteImport } from './routes/api/builders/track'
import { Route as ApiBuildersBuilderIdRouteImport } from './routes/api/builders/$builderId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAlertsTestTriggerRouteImport } from './routes/api/alerts/test-trigger'
import { Route as LandingLegalTermsRouteImport } from './routes/_landing/legal/terms'
import { Route as LandingLegalPrivacyRouteImport } from './routes/_landing/legal/privacy'
import { Route as LandingLegalImprintRouteImport } from './routes/_landing/legal/imprint'
import { Route as LandingLegalCookiesRouteImport } from './routes/_landing/legal/cookies'
import { Route as LandingChangelogSlugRouteImport } from './routes/_landing/changelog/$slug'
import { Route as LandingBlogSlugRouteImport } from './routes/_landing/blog/$slug'
import { Route as DashboardSettingsPrivacyRouteImport } from './routes/_dashboard/settings/privacy'
import { Route as DashboardSettingsBillingRouteImport } from './routes/_dashboard/settings/billing'
import { Route as DashboardAdminUsersRouteImport } from './routes/_dashboard/admin/users'
import { Route as DashboardAdminRoadmapRouteImport } from './routes/_dashboard/admin/roadmap'
import { Route as DashboardAdminPlanRequestsRouteImport } from './routes/_dashboard/admin/plan-requests'
import { Route as DashboardAdminMetricsRouteImport } from './routes/_dashboard/admin/metrics'
import { Route as DashboardAdminIncidentsRouteImport } from './routes/_dashboard/admin/incidents'
import { Route as DashboardAdminChangelogRouteImport } from './routes/_dashboard/admin/changelog'
import { Route as ApiMePlanChangesIndexRouteImport } from './routes/api/me/plan-changes/index'
import { Route as ApiMeDeleteAccountIndexRouteImport } from './routes/api/me/delete-account/index'
import { Route as ApiMeDataExportIndexRouteImport } from './routes/api/me/data-export/index'
import { Route as ApiMeBuildersIndexRouteImport } from './routes/api/me/builders/index'
import { Route as ApiMeBuilderIndexRouteImport } from './routes/api/me/builder/index'
import { Route as ApiBuildersRecentIndexRouteImport } from './routes/api/builders/recent/index'
import { Route as ApiAlertsTriggersIndexRouteImport } from './routes/api/alerts/triggers/index'
import { Route as ApiAdminUsersIndexRouteImport } from './routes/api/admin/users/index'
import { Route as ApiAdminRoadmapIndexRouteImport } from './routes/api/admin/roadmap/index'
import { Route as ApiAdminPlanRequestsIndexRouteImport } from './routes/api/admin/plan-requests/index'
import { Route as ApiAdminMetricsIndexRouteImport } from './routes/api/admin/metrics/index'
import { Route as ApiAdminIncidentsIndexRouteImport } from './routes/api/admin/incidents/index'
import { Route as ApiAdminChangelogIndexRouteImport } from './routes/api/admin/changelog/index'
import { Route as DashboardBuilderBuilderIdIndexRouteImport } from './routes/_dashboard/builder/$builderId/index'
import { Route as ApiMeDataExportIdRouteImport } from './routes/api/me/data-export/$id'
import { Route as ApiMeBuilderBuilderIdRouteImport } from './routes/api/me/builder/$builderId'
import { Route as ApiBuildersClaimVerifyRouteImport } from './routes/api/builders/claim/verify'
import { Route as ApiBuildersBuilderIdNotesRouteImport } from './routes/api/builders/$builderId/notes'
import { Route as ApiBuildersBuilderIdClaimRouteImport } from './routes/api/builders/$builderId/claim'
import { Route as ApiAlertsTriggersIdRouteImport } from './routes/api/alerts/triggers/$id'
import { Route as ApiAdminUsersUserIdRouteImport } from './routes/api/admin/users/$userId'
import { Route as ApiAdminRoadmapIdRouteImport } from './routes/api/admin/roadmap/$id'
import { Route as ApiAdminIncidentsIdRouteImport } from './routes/api/admin/incidents/$id'
import { Route as ApiAdminChangelogIdRouteImport } from './routes/api/admin/changelog/$id'
import { Route as ApiAdminAlertsRunWorkerRouteImport } from './routes/api/admin/alerts/run-worker'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRouteRoute = LandingRouteRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/onboarding/welcome',
  path: '/onboarding/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/onboarding/success',
  path: '/onboarding/success',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSearchRoute = OnboardingSearchRouteImport.update({
  id: '/onboarding/search',
  path: '/onboarding/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSaveRoute = OnboardingSaveRouteImport.update({
  id: '/onboarding/save',
  path: '/onboarding/save',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersBuilderIdRoute = BuildersBuilderIdRouteImport.update({
  id: '/builders/$builderId',
  path: '/builders/$builderId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAtomDotxmlRoute = BlogAtomDotxmlRouteImport.update({
  id: '/blog/atom.xml',
  path: '/blog/atom.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingStatusRoute = LandingStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingRoadmapRoute = LandingRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingPricingRoute = LandingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingChangelogRoute = LandingChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => LandingRouteRoute,
} as any)
const DashboardAlertsRoute = DashboardAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiStatusIndexRoute = ApiStatusIndexRouteImport.update({
  id: '/api/status/',
  path: '/api/status/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoadmapIndexRoute = ApiRoadmapIndexRouteImport.update({
  id: '/api/roadmap/',
  path: '/api/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecommendationsIndexRoute = ApiRecommendationsIndexRouteImport.update({
  id: '/api/recommendations/',
  path: '/api/recommendations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueriesIndexRoute = ApiQueriesIndexRouteImport.update({
  id: '/api/queries/',
  path: '/api/queries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIncidentsIndexRoute = ApiIncidentsIndexRouteImport.update({
  id: '/api/incidents/',
  path: '/api/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsentIndexRoute = ApiConsentIndexRouteImport.update({
  id: '/api/consent/',
  path: '/api/consent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChangelogIndexRoute = ApiChangelogIndexRouteImport.update({
  id: '/api/changelog/',
  path: '/api/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsIndexRoute = ApiAlertsIndexRouteImport.update({
  id: '/api/alerts/',
  path: '/api/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingExploreIndexRoute = LandingExploreIndexRouteImport.update({
  id: '/explore/',
  path: '/explore/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingChangelogIndexRoute = LandingChangelogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingChangelogRoute,
} as any)
const LandingBlogIndexRoute = LandingBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LandingRouteRoute,
} as any)
const DashboardSearchIndexRoute = DashboardSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMeIndexRoute = DashboardMeIndexRouteImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardExportsIndexRoute = DashboardExportsIndexRouteImport.update({
  id: '/exports/',
  path: '/exports/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiSearchBuildersRoute = ApiSearchBuildersRouteImport.update({
  id: '/api/search/builders',
  path: '/api/search/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansRequestUpgradeRoute = ApiPlansRequestUpgradeRouteImport.update({
  id: '/api/plans/request-upgrade',
  path: '/api/plans/request-upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlansMeRoute = ApiPlansMeRouteImport.update({
  id: '/api/plans/me',
  path: '/api/plans/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingStatusRoute = ApiOnboardingStatusRouteImport.update({
  id: '/api/onboarding/status',
  path: '/api/onboarding/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingSkipRoute = ApiOnboardingSkipRouteImport.update({
  id: '/api/onboarding/skip',
  path: '/api/onboarding/skip',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingCompleteRoute = ApiOnboardingCompleteRouteImport.update({
  id: '/api/onboarding/complete',
  path: '/api/onboarding/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgExploreRoute = ApiOgExploreRouteImport.update({
  id: '/api/og/explore',
  path: '/api/og/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedsSearchIdRoute = ApiFeedsSearchIdRouteImport.update({
  id: '/api/feeds/$searchId',
  path: '/api/feeds/$searchId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportBuildersRoute = ApiExportBuildersRouteImport.update({
  id: '/api/export/builders',
  path: '/api/export/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDashboardStatsRoute = ApiDashboardStatsRouteImport.update({
  id: '/api/dashboard/stats',
  path: '/api/dashboard/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChangelogSlugRoute = ApiChangelogSlugRouteImport.update({
  id: '/api/changelog/$slug',
  path: '/api/changelog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildersTrackRoute = ApiBuildersTrackRouteImport.update({
  id: '/api/builders/track',
  path: '/api/builders/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildersBuilderIdRoute = ApiBuildersBuilderIdRouteImport.update({
  id: '/api/builders/$builderId',
  path: '/api/builders/$builderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsTestTriggerRoute = ApiAlertsTestTriggerRouteImport.update({
  id: '/api/alerts/test-trigger',
  path: '/api/alerts/test-trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingLegalTermsRoute = LandingLegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingLegalPrivacyRoute = LandingLegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingLegalImprintRoute = LandingLegalImprintRouteImport.update({
  id: '/legal/imprint',
  path: '/legal/imprint',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingLegalCookiesRoute = LandingLegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => LandingRouteRoute,
} as any)
const LandingChangelogSlugRoute = LandingChangelogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LandingChangelogRoute,
} as any)
const LandingBlogSlugRoute = LandingBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LandingRouteRoute,
} as any)
const DashboardSettingsPrivacyRoute =
  DashboardSettingsPrivacyRouteImport.update({
    id: '/settings/privacy',
    path: '/settings/privacy',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSettingsBillingRoute =
  DashboardSettingsBillingRouteImport.update({
    id: '/settings/billing',
    path: '/settings/billing',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminRoadmapRoute = DashboardAdminRoadmapRouteImport.update({
  id: '/admin/roadmap',
  path: '/admin/roadmap',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminPlanRequestsRoute =
  DashboardAdminPlanRequestsRouteImport.update({
    id: '/admin/plan-requests',
    path: '/admin/plan-requests',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardAdminMetricsRoute = DashboardAdminMetricsRouteImport.update({
  id: '/admin/metrics',
  path: '/admin/metrics',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminIncidentsRoute = DashboardAdminIncidentsRouteImport.update({
  id: '/admin/incidents',
  path: '/admin/incidents',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminChangelogRoute = DashboardAdminChangelogRouteImport.update({
  id: '/admin/changelog',
  path: '/admin/changelog',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiMePlanChangesIndexRoute = ApiMePlanChangesIndexRouteImport.update({
  id: '/api/me/plan-changes/',
  path: '/api/me/plan-changes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeDeleteAccountIndexRoute = ApiMeDeleteAccountIndexRouteImport.update({
  id: '/api/me/delete-account/',
  path: '/api/me/delete-account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeDataExportIndexRoute = ApiMeDataExportIndexRouteImport.update({
  id: '/api/me/data-export/',
  path: '/api/me/data-export/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeBuildersIndexRoute = ApiMeBuildersIndexRouteImport.update({
  id: '/api/me/builders/',
  path: '/api/me/builders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeBuilderIndexRoute = ApiMeBuilderIndexRouteImport.update({
  id: '/api/me/builder/',
  path: '/api/me/builder/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildersRecentIndexRoute = ApiBuildersRecentIndexRouteImport.update({
  id: '/api/builders/recent/',
  path: '/api/builders/recent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlertsTriggersIndexRoute = ApiAlertsTriggersIndexRouteImport.update({
  id: '/api/alerts/triggers/',
  path: '/api/alerts/triggers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersIndexRoute = ApiAdminUsersIndexRouteImport.update({
  id: '/api/admin/users/',
  path: '/api/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoadmapIndexRoute = ApiAdminRoadmapIndexRouteImport.update({
  id: '/api/admin/roadmap/',
  path: '/api/admin/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPlanRequestsIndexRoute =
  ApiAdminPlanRequestsIndexRouteImport.update({
    id: '/api/admin/plan-requests/',
    path: '/api/admin/plan-requests/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminMetricsIndexRoute = ApiAdminMetricsIndexRouteImport.update({
  id: '/api/admin/metrics/',
  path: '/api/admin/metrics/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIncidentsIndexRoute = ApiAdminIncidentsIndexRouteImport.update({
  id: '/api/admin/incidents/',
  path: '/api/admin/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminChangelogIndexRoute = ApiAdminChangelogIndexRouteImport.update({
  id: '/api/admin/changelog/',
  path: '/api/admin/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBuilderBuilderIdIndexRoute =
  DashboardBuilderBuilderIdIndexRouteImport.update({
    id: '/builder/$builderId/',
    path: '/builder/$builderId/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const ApiMeDataExportIdRoute = ApiMeDataExportIdRouteImport.update({
  id: '/api/me/data-export/$id',
  path: '/api/me/data-export/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeBuilderBuilderIdRoute = ApiMeBuilderBuilderIdRouteImport.update({
  id: '/api/me/builder/$builderId',
  path: '/api/me/builder/$builderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildersClaimVerifyRoute = ApiBuildersClaimVerifyRouteImport.update({
  id: '/api/builders/claim/verify',
  path: '/api/builders/claim/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBuildersBuilderIdNotesRoute =
  ApiBuildersBuilderIdNotesRouteImport.update({
    id: '/notes',
    path: '/notes',
    getParentRoute: () => ApiBuildersBuilderIdRoute,
  } as any)
const ApiBuildersBuilderIdClaimRoute =
  ApiBuildersBuilderIdClaimRouteImport.update({
    id: '/claim',
    path: '/claim',
    getParentRoute: () => ApiBuildersBuilderIdRoute,
  } as any)
const ApiAlertsTriggersIdRoute = ApiAlertsTriggersIdRouteImport.update({
  id: '/api/alerts/triggers/$id',
  path: '/api/alerts/triggers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersUserIdRoute = ApiAdminUsersUserIdRouteImport.update({
  id: '/api/admin/users/$userId',
  path: '/api/admin/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRoadmapIdRoute = ApiAdminRoadmapIdRouteImport.update({
  id: '/api/admin/roadmap/$id',
  path: '/api/admin/roadmap/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminIncidentsIdRoute = ApiAdminIncidentsIdRouteImport.update({
  id: '/api/admin/incidents/$id',
  path: '/api/admin/incidents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminChangelogIdRoute = ApiAdminChangelogIdRouteImport.update({
  id: '/api/admin/changelog/$id',
  path: '/api/admin/changelog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAlertsRunWorkerRoute = ApiAdminAlertsRunWorkerRouteImport.update({
  id: '/api/admin/alerts/run-worker',
  path: '/api/admin/alerts/run-worker',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alerts': typeof DashboardAlertsRoute
  '/changelog': typeof LandingChangelogRouteWithChildren
  '/pricing': typeof LandingPricingRoute
  '/roadmap': typeof LandingRoadmapRoute
  '/status': typeof LandingStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/blog/atom.xml': typeof BlogAtomDotxmlRoute
  '/builders/$builderId': typeof BuildersBuilderIdRoute
  '/onboarding/save': typeof OnboardingSaveRoute
  '/onboarding/search': typeof OnboardingSearchRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/admin/changelog': typeof DashboardAdminChangelogRoute
  '/admin/incidents': typeof DashboardAdminIncidentsRoute
  '/admin/metrics': typeof DashboardAdminMetricsRoute
  '/admin/plan-requests': typeof DashboardAdminPlanRequestsRoute
  '/admin/roadmap': typeof DashboardAdminRoadmapRoute
  '/admin/users': typeof DashboardAdminUsersRoute
  '/settings/billing': typeof DashboardSettingsBillingRoute
  '/settings/privacy': typeof DashboardSettingsPrivacyRoute
  '/blog/$slug': typeof LandingBlogSlugRoute
  '/changelog/$slug': typeof LandingChangelogSlugRoute
  '/legal/cookies': typeof LandingLegalCookiesRoute
  '/legal/imprint': typeof LandingLegalImprintRoute
  '/legal/privacy': typeof LandingLegalPrivacyRoute
  '/legal/terms': typeof LandingLegalTermsRoute
  '/api/alerts/test-trigger': typeof ApiAlertsTestTriggerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builders/$builderId': typeof ApiBuildersBuilderIdRouteWithChildren
  '/api/builders/track': typeof ApiBuildersTrackRoute
  '/api/changelog/$slug': typeof ApiChangelogSlugRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/export/builders': typeof ApiExportBuildersRoute
  '/api/feeds/$searchId': typeof ApiFeedsSearchIdRoute
  '/api/og/explore': typeof ApiOgExploreRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/skip': typeof ApiOnboardingSkipRoute
  '/api/onboarding/status': typeof ApiOnboardingStatusRoute
  '/api/plans/me': typeof ApiPlansMeRoute
  '/api/plans/request-upgrade': typeof ApiPlansRequestUpgradeRoute
  '/api/search/builders': typeof ApiSearchBuildersRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/exports/': typeof DashboardExportsIndexRoute
  '/me/': typeof DashboardMeIndexRoute
  '/search/': typeof DashboardSearchIndexRoute
  '/blog/': typeof LandingBlogIndexRoute
  '/changelog/': typeof LandingChangelogIndexRoute
  '/explore/': typeof LandingExploreIndexRoute
  '/api/alerts/': typeof ApiAlertsIndexRoute
  '/api/changelog/': typeof ApiChangelogIndexRoute
  '/api/consent/': typeof ApiConsentIndexRoute
  '/api/incidents/': typeof ApiIncidentsIndexRoute
  '/api/queries/': typeof ApiQueriesIndexRoute
  '/api/recommendations/': typeof ApiRecommendationsIndexRoute
  '/api/roadmap/': typeof ApiRoadmapIndexRoute
  '/api/status/': typeof ApiStatusIndexRoute
  '/api/admin/alerts/run-worker': typeof ApiAdminAlertsRunWorkerRoute
  '/api/admin/changelog/$id': typeof ApiAdminChangelogIdRoute
  '/api/admin/incidents/$id': typeof ApiAdminIncidentsIdRoute
  '/api/admin/roadmap/$id': typeof ApiAdminRoadmapIdRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/alerts/triggers/$id': typeof ApiAlertsTriggersIdRoute
  '/api/builders/$builderId/claim': typeof ApiBuildersBuilderIdClaimRoute
  '/api/builders/$builderId/notes': typeof ApiBuildersBuilderIdNotesRoute
  '/api/builders/claim/verify': typeof ApiBuildersClaimVerifyRoute
  '/api/me/builder/$builderId': typeof ApiMeBuilderBuilderIdRoute
  '/api/me/data-export/$id': typeof ApiMeDataExportIdRoute
  '/builder/$builderId/': typeof DashboardBuilderBuilderIdIndexRoute
  '/api/admin/changelog/': typeof ApiAdminChangelogIndexRoute
  '/api/admin/incidents/': typeof ApiAdminIncidentsIndexRoute
  '/api/admin/metrics/': typeof ApiAdminMetricsIndexRoute
  '/api/admin/plan-requests/': typeof ApiAdminPlanRequestsIndexRoute
  '/api/admin/roadmap/': typeof ApiAdminRoadmapIndexRoute
  '/api/admin/users/': typeof ApiAdminUsersIndexRoute
  '/api/alerts/triggers/': typeof ApiAlertsTriggersIndexRoute
  '/api/builders/recent/': typeof ApiBuildersRecentIndexRoute
  '/api/me/builder/': typeof ApiMeBuilderIndexRoute
  '/api/me/builders/': typeof ApiMeBuildersIndexRoute
  '/api/me/data-export/': typeof ApiMeDataExportIndexRoute
  '/api/me/delete-account/': typeof ApiMeDeleteAccountIndexRoute
  '/api/me/plan-changes/': typeof ApiMePlanChangesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LandingIndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/alerts': typeof DashboardAlertsRoute
  '/pricing': typeof LandingPricingRoute
  '/roadmap': typeof LandingRoadmapRoute
  '/status': typeof LandingStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/blog/atom.xml': typeof BlogAtomDotxmlRoute
  '/builders/$builderId': typeof BuildersBuilderIdRoute
  '/onboarding/save': typeof OnboardingSaveRoute
  '/onboarding/search': typeof OnboardingSearchRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/admin/changelog': typeof DashboardAdminChangelogRoute
  '/admin/incidents': typeof DashboardAdminIncidentsRoute
  '/admin/metrics': typeof DashboardAdminMetricsRoute
  '/admin/plan-requests': typeof DashboardAdminPlanRequestsRoute
  '/admin/roadmap': typeof DashboardAdminRoadmapRoute
  '/admin/users': typeof DashboardAdminUsersRoute
  '/settings/billing': typeof DashboardSettingsBillingRoute
  '/settings/privacy': typeof DashboardSettingsPrivacyRoute
  '/blog/$slug': typeof LandingBlogSlugRoute
  '/changelog/$slug': typeof LandingChangelogSlugRoute
  '/legal/cookies': typeof LandingLegalCookiesRoute
  '/legal/imprint': typeof LandingLegalImprintRoute
  '/legal/privacy': typeof LandingLegalPrivacyRoute
  '/legal/terms': typeof LandingLegalTermsRoute
  '/api/alerts/test-trigger': typeof ApiAlertsTestTriggerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builders/$builderId': typeof ApiBuildersBuilderIdRouteWithChildren
  '/api/builders/track': typeof ApiBuildersTrackRoute
  '/api/changelog/$slug': typeof ApiChangelogSlugRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/export/builders': typeof ApiExportBuildersRoute
  '/api/feeds/$searchId': typeof ApiFeedsSearchIdRoute
  '/api/og/explore': typeof ApiOgExploreRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/skip': typeof ApiOnboardingSkipRoute
  '/api/onboarding/status': typeof ApiOnboardingStatusRoute
  '/api/plans/me': typeof ApiPlansMeRoute
  '/api/plans/request-upgrade': typeof ApiPlansRequestUpgradeRoute
  '/api/search/builders': typeof ApiSearchBuildersRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/exports': typeof DashboardExportsIndexRoute
  '/me': typeof DashboardMeIndexRoute
  '/search': typeof DashboardSearchIndexRoute
  '/blog': typeof LandingBlogIndexRoute
  '/changelog': typeof LandingChangelogIndexRoute
  '/explore': typeof LandingExploreIndexRoute
  '/api/alerts': typeof ApiAlertsIndexRoute
  '/api/changelog': typeof ApiChangelogIndexRoute
  '/api/consent': typeof ApiConsentIndexRoute
  '/api/incidents': typeof ApiIncidentsIndexRoute
  '/api/queries': typeof ApiQueriesIndexRoute
  '/api/recommendations': typeof ApiRecommendationsIndexRoute
  '/api/roadmap': typeof ApiRoadmapIndexRoute
  '/api/status': typeof ApiStatusIndexRoute
  '/api/admin/alerts/run-worker': typeof ApiAdminAlertsRunWorkerRoute
  '/api/admin/changelog/$id': typeof ApiAdminChangelogIdRoute
  '/api/admin/incidents/$id': typeof ApiAdminIncidentsIdRoute
  '/api/admin/roadmap/$id': typeof ApiAdminRoadmapIdRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/alerts/triggers/$id': typeof ApiAlertsTriggersIdRoute
  '/api/builders/$builderId/claim': typeof ApiBuildersBuilderIdClaimRoute
  '/api/builders/$builderId/notes': typeof ApiBuildersBuilderIdNotesRoute
  '/api/builders/claim/verify': typeof ApiBuildersClaimVerifyRoute
  '/api/me/builder/$builderId': typeof ApiMeBuilderBuilderIdRoute
  '/api/me/data-export/$id': typeof ApiMeDataExportIdRoute
  '/builder/$builderId': typeof DashboardBuilderBuilderIdIndexRoute
  '/api/admin/changelog': typeof ApiAdminChangelogIndexRoute
  '/api/admin/incidents': typeof ApiAdminIncidentsIndexRoute
  '/api/admin/metrics': typeof ApiAdminMetricsIndexRoute
  '/api/admin/plan-requests': typeof ApiAdminPlanRequestsIndexRoute
  '/api/admin/roadmap': typeof ApiAdminRoadmapIndexRoute
  '/api/admin/users': typeof ApiAdminUsersIndexRoute
  '/api/alerts/triggers': typeof ApiAlertsTriggersIndexRoute
  '/api/builders/recent': typeof ApiBuildersRecentIndexRoute
  '/api/me/builder': typeof ApiMeBuilderIndexRoute
  '/api/me/builders': typeof ApiMeBuildersIndexRoute
  '/api/me/data-export': typeof ApiMeDataExportIndexRoute
  '/api/me/delete-account': typeof ApiMeDeleteAccountIndexRoute
  '/api/me/plan-changes': typeof ApiMePlanChangesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/_landing': typeof LandingRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_dashboard/alerts': typeof DashboardAlertsRoute
  '/_landing/changelog': typeof LandingChangelogRouteWithChildren
  '/_landing/pricing': typeof LandingPricingRoute
  '/_landing/roadmap': typeof LandingRoadmapRoute
  '/_landing/status': typeof LandingStatusRoute
  '/api/health': typeof ApiHealthRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/blog/atom.xml': typeof BlogAtomDotxmlRoute
  '/builders/$builderId': typeof BuildersBuilderIdRoute
  '/onboarding/save': typeof OnboardingSaveRoute
  '/onboarding/search': typeof OnboardingSearchRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/_landing/': typeof LandingIndexRoute
  '/_dashboard/admin/changelog': typeof DashboardAdminChangelogRoute
  '/_dashboard/admin/incidents': typeof DashboardAdminIncidentsRoute
  '/_dashboard/admin/metrics': typeof DashboardAdminMetricsRoute
  '/_dashboard/admin/plan-requests': typeof DashboardAdminPlanRequestsRoute
  '/_dashboard/admin/roadmap': typeof DashboardAdminRoadmapRoute
  '/_dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/_dashboard/settings/billing': typeof DashboardSettingsBillingRoute
  '/_dashboard/settings/privacy': typeof DashboardSettingsPrivacyRoute
  '/_landing/blog/$slug': typeof LandingBlogSlugRoute
  '/_landing/changelog/$slug': typeof LandingChangelogSlugRoute
  '/_landing/legal/cookies': typeof LandingLegalCookiesRoute
  '/_landing/legal/imprint': typeof LandingLegalImprintRoute
  '/_landing/legal/privacy': typeof LandingLegalPrivacyRoute
  '/_landing/legal/terms': typeof LandingLegalTermsRoute
  '/api/alerts/test-trigger': typeof ApiAlertsTestTriggerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/builders/$builderId': typeof ApiBuildersBuilderIdRouteWithChildren
  '/api/builders/track': typeof ApiBuildersTrackRoute
  '/api/changelog/$slug': typeof ApiChangelogSlugRoute
  '/api/dashboard/stats': typeof ApiDashboardStatsRoute
  '/api/export/builders': typeof ApiExportBuildersRoute
  '/api/feeds/$searchId': typeof ApiFeedsSearchIdRoute
  '/api/og/explore': typeof ApiOgExploreRoute
  '/api/onboarding/complete': typeof ApiOnboardingCompleteRoute
  '/api/onboarding/skip': typeof ApiOnboardingSkipRoute
  '/api/onboarding/status': typeof ApiOnboardingStatusRoute
  '/api/plans/me': typeof ApiPlansMeRoute
  '/api/plans/request-upgrade': typeof ApiPlansRequestUpgradeRoute
  '/api/search/builders': typeof ApiSearchBuildersRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/_dashboard/exports/': typeof DashboardExportsIndexRoute
  '/_dashboard/me/': typeof DashboardMeIndexRoute
  '/_dashboard/search/': typeof DashboardSearchIndexRoute
  '/_landing/blog/': typeof LandingBlogIndexRoute
  '/_landing/changelog/': typeof LandingChangelogIndexRoute
  '/_landing/explore/': typeof LandingExploreIndexRoute
  '/api/alerts/': typeof ApiAlertsIndexRoute
  '/api/changelog/': typeof ApiChangelogIndexRoute
  '/api/consent/': typeof ApiConsentIndexRoute
  '/api/incidents/': typeof ApiIncidentsIndexRoute
  '/api/queries/': typeof ApiQueriesIndexRoute
  '/api/recommendations/': typeof ApiRecommendationsIndexRoute
  '/api/roadmap/': typeof ApiRoadmapIndexRoute
  '/api/status/': typeof ApiStatusIndexRoute
  '/api/admin/alerts/run-worker': typeof ApiAdminAlertsRunWorkerRoute
  '/api/admin/changelog/$id': typeof ApiAdminChangelogIdRoute
  '/api/admin/incidents/$id': typeof ApiAdminIncidentsIdRoute
  '/api/admin/roadmap/$id': typeof ApiAdminRoadmapIdRoute
  '/api/admin/users/$userId': typeof ApiAdminUsersUserIdRoute
  '/api/alerts/triggers/$id': typeof ApiAlertsTriggersIdRoute
  '/api/builders/$builderId/claim': typeof ApiBuildersBuilderIdClaimRoute
  '/api/builders/$builderId/notes': typeof ApiBuildersBuilderIdNotesRoute
  '/api/builders/claim/verify': typeof ApiBuildersClaimVerifyRoute
  '/api/me/builder/$builderId': typeof ApiMeBuilderBuilderIdRoute
  '/api/me/data-export/$id': typeof ApiMeDataExportIdRoute
  '/_dashboard/builder/$builderId/': typeof DashboardBuilderBuilderIdIndexRoute
  '/api/admin/changelog/': typeof ApiAdminChangelogIndexRoute
  '/api/admin/incidents/': typeof ApiAdminIncidentsIndexRoute
  '/api/admin/metrics/': typeof ApiAdminMetricsIndexRoute
  '/api/admin/plan-requests/': typeof ApiAdminPlanRequestsIndexRoute
  '/api/admin/roadmap/': typeof ApiAdminRoadmapIndexRoute
  '/api/admin/users/': typeof ApiAdminUsersIndexRoute
  '/api/alerts/triggers/': typeof ApiAlertsTriggersIndexRoute
  '/api/builders/recent/': typeof ApiBuildersRecentIndexRoute
  '/api/me/builder/': typeof ApiMeBuilderIndexRoute
  '/api/me/builders/': typeof ApiMeBuildersIndexRoute
  '/api/me/data-export/': typeof ApiMeDataExportIndexRoute
  '/api/me/delete-account/': typeof ApiMeDeleteAccountIndexRoute
  '/api/me/plan-changes/': typeof ApiMePlanChangesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/alerts'
    | '/changelog'
    | '/pricing'
    | '/roadmap'
    | '/status'
    | '/api/health'
    | '/auth/forgot'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/blog/atom.xml'
    | '/builders/$builderId'
    | '/onboarding/save'
    | '/onboarding/search'
    | '/onboarding/success'
    | '/onboarding/welcome'
    | '/admin/changelog'
    | '/admin/incidents'
    | '/admin/metrics'
    | '/admin/plan-requests'
    | '/admin/roadmap'
    | '/admin/users'
    | '/settings/billing'
    | '/settings/privacy'
    | '/blog/$slug'
    | '/changelog/$slug'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/api/alerts/test-trigger'
    | '/api/auth/$'
    | '/api/builders/$builderId'
    | '/api/builders/track'
    | '/api/changelog/$slug'
    | '/api/dashboard/stats'
    | '/api/export/builders'
    | '/api/feeds/$searchId'
    | '/api/og/explore'
    | '/api/onboarding/complete'
    | '/api/onboarding/skip'
    | '/api/onboarding/status'
    | '/api/plans/me'
    | '/api/plans/request-upgrade'
    | '/api/search/builders'
    | '/dashboard/'
    | '/exports/'
    | '/me/'
    | '/search/'
    | '/blog/'
    | '/changelog/'
    | '/explore/'
    | '/api/alerts/'
    | '/api/changelog/'
    | '/api/consent/'
    | '/api/incidents/'
    | '/api/queries/'
    | '/api/recommendations/'
    | '/api/roadmap/'
    | '/api/status/'
    | '/api/admin/alerts/run-worker'
    | '/api/admin/changelog/$id'
    | '/api/admin/incidents/$id'
    | '/api/admin/roadmap/$id'
    | '/api/admin/users/$userId'
    | '/api/alerts/triggers/$id'
    | '/api/builders/$builderId/claim'
    | '/api/builders/$builderId/notes'
    | '/api/builders/claim/verify'
    | '/api/me/builder/$builderId'
    | '/api/me/data-export/$id'
    | '/builder/$builderId/'
    | '/api/admin/changelog/'
    | '/api/admin/incidents/'
    | '/api/admin/metrics/'
    | '/api/admin/plan-requests/'
    | '/api/admin/roadmap/'
    | '/api/admin/users/'
    | '/api/alerts/triggers/'
    | '/api/builders/recent/'
    | '/api/me/builder/'
    | '/api/me/builders/'
    | '/api/me/data-export/'
    | '/api/me/delete-account/'
    | '/api/me/plan-changes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/alerts'
    | '/pricing'
    | '/roadmap'
    | '/status'
    | '/api/health'
    | '/auth/forgot'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/blog/atom.xml'
    | '/builders/$builderId'
    | '/onboarding/save'
    | '/onboarding/search'
    | '/onboarding/success'
    | '/onboarding/welcome'
    | '/admin/changelog'
    | '/admin/incidents'
    | '/admin/metrics'
    | '/admin/plan-requests'
    | '/admin/roadmap'
    | '/admin/users'
    | '/settings/billing'
    | '/settings/privacy'
    | '/blog/$slug'
    | '/changelog/$slug'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/api/alerts/test-trigger'
    | '/api/auth/$'
    | '/api/builders/$builderId'
    | '/api/builders/track'
    | '/api/changelog/$slug'
    | '/api/dashboard/stats'
    | '/api/export/builders'
    | '/api/feeds/$searchId'
    | '/api/og/explore'
    | '/api/onboarding/complete'
    | '/api/onboarding/skip'
    | '/api/onboarding/status'
    | '/api/plans/me'
    | '/api/plans/request-upgrade'
    | '/api/search/builders'
    | '/dashboard'
    | '/exports'
    | '/me'
    | '/search'
    | '/blog'
    | '/changelog'
    | '/explore'
    | '/api/alerts'
    | '/api/changelog'
    | '/api/consent'
    | '/api/incidents'
    | '/api/queries'
    | '/api/recommendations'
    | '/api/roadmap'
    | '/api/status'
    | '/api/admin/alerts/run-worker'
    | '/api/admin/changelog/$id'
    | '/api/admin/incidents/$id'
    | '/api/admin/roadmap/$id'
    | '/api/admin/users/$userId'
    | '/api/alerts/triggers/$id'
    | '/api/builders/$builderId/claim'
    | '/api/builders/$builderId/notes'
    | '/api/builders/claim/verify'
    | '/api/me/builder/$builderId'
    | '/api/me/data-export/$id'
    | '/builder/$builderId'
    | '/api/admin/changelog'
    | '/api/admin/incidents'
    | '/api/admin/metrics'
    | '/api/admin/plan-requests'
    | '/api/admin/roadmap'
    | '/api/admin/users'
    | '/api/alerts/triggers'
    | '/api/builders/recent'
    | '/api/me/builder'
    | '/api/me/builders'
    | '/api/me/data-export'
    | '/api/me/delete-account'
    | '/api/me/plan-changes'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_landing'
    | '/auth'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_dashboard/alerts'
    | '/_landing/changelog'
    | '/_landing/pricing'
    | '/_landing/roadmap'
    | '/_landing/status'
    | '/api/health'
    | '/auth/forgot'
    | '/auth/reset'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/blog/atom.xml'
    | '/builders/$builderId'
    | '/onboarding/save'
    | '/onboarding/search'
    | '/onboarding/success'
    | '/onboarding/welcome'
    | '/_landing/'
    | '/_dashboard/admin/changelog'
    | '/_dashboard/admin/incidents'
    | '/_dashboard/admin/metrics'
    | '/_dashboard/admin/plan-requests'
    | '/_dashboard/admin/roadmap'
    | '/_dashboard/admin/users'
    | '/_dashboard/settings/billing'
    | '/_dashboard/settings/privacy'
    | '/_landing/blog/$slug'
    | '/_landing/changelog/$slug'
    | '/_landing/legal/cookies'
    | '/_landing/legal/imprint'
    | '/_landing/legal/privacy'
    | '/_landing/legal/terms'
    | '/api/alerts/test-trigger'
    | '/api/auth/$'
    | '/api/builders/$builderId'
    | '/api/builders/track'
    | '/api/changelog/$slug'
    | '/api/dashboard/stats'
    | '/api/export/builders'
    | '/api/feeds/$searchId'
    | '/api/og/explore'
    | '/api/onboarding/complete'
    | '/api/onboarding/skip'
    | '/api/onboarding/status'
    | '/api/plans/me'
    | '/api/plans/request-upgrade'
    | '/api/search/builders'
    | '/_dashboard/dashboard/'
    | '/_dashboard/exports/'
    | '/_dashboard/me/'
    | '/_dashboard/search/'
    | '/_landing/blog/'
    | '/_landing/changelog/'
    | '/_landing/explore/'
    | '/api/alerts/'
    | '/api/changelog/'
    | '/api/consent/'
    | '/api/incidents/'
    | '/api/queries/'
    | '/api/recommendations/'
    | '/api/roadmap/'
    | '/api/status/'
    | '/api/admin/alerts/run-worker'
    | '/api/admin/changelog/$id'
    | '/api/admin/incidents/$id'
    | '/api/admin/roadmap/$id'
    | '/api/admin/users/$userId'
    | '/api/alerts/triggers/$id'
    | '/api/builders/$builderId/claim'
    | '/api/builders/$builderId/notes'
    | '/api/builders/claim/verify'
    | '/api/me/builder/$builderId'
    | '/api/me/data-export/$id'
    | '/_dashboard/builder/$builderId/'
    | '/api/admin/changelog/'
    | '/api/admin/incidents/'
    | '/api/admin/metrics/'
    | '/api/admin/plan-requests/'
    | '/api/admin/roadmap/'
    | '/api/admin/users/'
    | '/api/alerts/triggers/'
    | '/api/builders/recent/'
    | '/api/me/builder/'
    | '/api/me/builders/'
    | '/api/me/data-export/'
    | '/api/me/delete-account/'
    | '/api/me/plan-changes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LandingRouteRoute: typeof LandingRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthRoute: typeof ApiHealthRoute
  BlogAtomDotxmlRoute: typeof BlogAtomDotxmlRoute
  BuildersBuilderIdRoute: typeof BuildersBuilderIdRoute
  OnboardingSaveRoute: typeof OnboardingSaveRoute
  OnboardingSearchRoute: typeof OnboardingSearchRoute
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  ApiAlertsTestTriggerRoute: typeof ApiAlertsTestTriggerRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBuildersBuilderIdRoute: typeof ApiBuildersBuilderIdRouteWithChildren
  ApiBuildersTrackRoute: typeof ApiBuildersTrackRoute
  ApiChangelogSlugRoute: typeof ApiChangelogSlugRoute
  ApiDashboardStatsRoute: typeof ApiDashboardStatsRoute
  ApiExportBuildersRoute: typeof ApiExportBuildersRoute
  ApiFeedsSearchIdRoute: typeof ApiFeedsSearchIdRoute
  ApiOgExploreRoute: typeof ApiOgExploreRoute
  ApiOnboardingCompleteRoute: typeof ApiOnboardingCompleteRoute
  ApiOnboardingSkipRoute: typeof ApiOnboardingSkipRoute
  ApiOnboardingStatusRoute: typeof ApiOnboardingStatusRoute
  ApiPlansMeRoute: typeof ApiPlansMeRoute
  ApiPlansRequestUpgradeRoute: typeof ApiPlansRequestUpgradeRoute
  ApiSearchBuildersRoute: typeof ApiSearchBuildersRoute
  ApiAlertsIndexRoute: typeof ApiAlertsIndexRoute
  ApiChangelogIndexRoute: typeof ApiChangelogIndexRoute
  ApiConsentIndexRoute: typeof ApiConsentIndexRoute
  ApiIncidentsIndexRoute: typeof ApiIncidentsIndexRoute
  ApiQueriesIndexRoute: typeof ApiQueriesIndexRoute
  ApiRecommendationsIndexRoute: typeof ApiRecommendationsIndexRoute
  ApiRoadmapIndexRoute: typeof ApiRoadmapIndexRoute
  ApiStatusIndexRoute: typeof ApiStatusIndexRoute
  ApiAdminAlertsRunWorkerRoute: typeof ApiAdminAlertsRunWorkerRoute
  ApiAdminChangelogIdRoute: typeof ApiAdminChangelogIdRoute
  ApiAdminIncidentsIdRoute: typeof ApiAdminIncidentsIdRoute
  ApiAdminRoadmapIdRoute: typeof ApiAdminRoadmapIdRoute
  ApiAdminUsersUserIdRoute: typeof ApiAdminUsersUserIdRoute
  ApiAlertsTriggersIdRoute: typeof ApiAlertsTriggersIdRoute
  ApiBuildersClaimVerifyRoute: typeof ApiBuildersClaimVerifyRoute
  ApiMeBuilderBuilderIdRoute: typeof ApiMeBuilderBuilderIdRoute
  ApiMeDataExportIdRoute: typeof ApiMeDataExportIdRoute
  ApiAdminChangelogIndexRoute: typeof ApiAdminChangelogIndexRoute
  ApiAdminIncidentsIndexRoute: typeof ApiAdminIncidentsIndexRoute
  ApiAdminMetricsIndexRoute: typeof ApiAdminMetricsIndexRoute
  ApiAdminPlanRequestsIndexRoute: typeof ApiAdminPlanRequestsIndexRoute
  ApiAdminRoadmapIndexRoute: typeof ApiAdminRoadmapIndexRoute
  ApiAdminUsersIndexRoute: typeof ApiAdminUsersIndexRoute
  ApiAlertsTriggersIndexRoute: typeof ApiAlertsTriggersIndexRoute
  ApiBuildersRecentIndexRoute: typeof ApiBuildersRecentIndexRoute
  ApiMeBuilderIndexRoute: typeof ApiMeBuilderIndexRoute
  ApiMeBuildersIndexRoute: typeof ApiMeBuildersIndexRoute
  ApiMeDataExportIndexRoute: typeof ApiMeDataExportIndexRoute
  ApiMeDeleteAccountIndexRoute: typeof ApiMeDeleteAccountIndexRoute
  ApiMePlanChangesIndexRoute: typeof ApiMePlanChangesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/success': {
      id: '/onboarding/success'
      path: '/onboarding/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/search': {
      id: '/onboarding/search'
      path: '/onboarding/search'
      fullPath: '/onboarding/search'
      preLoaderRoute: typeof OnboardingSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/save': {
      id: '/onboarding/save'
      path: '/onboarding/save'
      fullPath: '/onboarding/save'
      preLoaderRoute: typeof OnboardingSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders/$builderId': {
      id: '/builders/$builderId'
      path: '/builders/$builderId'
      fullPath: '/builders/$builderId'
      preLoaderRoute: typeof BuildersBuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/atom.xml': {
      id: '/blog/atom.xml'
      path: '/blog/atom.xml'
      fullPath: '/blog/atom.xml'
      preLoaderRoute: typeof BlogAtomDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/status': {
      id: '/_landing/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof LandingStatusRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/roadmap': {
      id: '/_landing/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof LandingRoadmapRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/pricing': {
      id: '/_landing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof LandingPricingRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/changelog': {
      id: '/_landing/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof LandingChangelogRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_dashboard/alerts': {
      id: '/_dashboard/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof DashboardAlertsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/status/': {
      id: '/api/status/'
      path: '/api/status'
      fullPath: '/api/status/'
      preLoaderRoute: typeof ApiStatusIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/roadmap/': {
      id: '/api/roadmap/'
      path: '/api/roadmap'
      fullPath: '/api/roadmap/'
      preLoaderRoute: typeof ApiRoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recommendations/': {
      id: '/api/recommendations/'
      path: '/api/recommendations'
      fullPath: '/api/recommendations/'
      preLoaderRoute: typeof ApiRecommendationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/queries/': {
      id: '/api/queries/'
      path: '/api/queries'
      fullPath: '/api/queries/'
      preLoaderRoute: typeof ApiQueriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/incidents/': {
      id: '/api/incidents/'
      path: '/api/incidents'
      fullPath: '/api/incidents/'
      preLoaderRoute: typeof ApiIncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consent/': {
      id: '/api/consent/'
      path: '/api/consent'
      fullPath: '/api/consent/'
      preLoaderRoute: typeof ApiConsentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/changelog/': {
      id: '/api/changelog/'
      path: '/api/changelog'
      fullPath: '/api/changelog/'
      preLoaderRoute: typeof ApiChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/': {
      id: '/api/alerts/'
      path: '/api/alerts'
      fullPath: '/api/alerts/'
      preLoaderRoute: typeof ApiAlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/explore/': {
      id: '/_landing/explore/'
      path: '/explore'
      fullPath: '/explore/'
      preLoaderRoute: typeof LandingExploreIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/changelog/': {
      id: '/_landing/changelog/'
      path: '/'
      fullPath: '/changelog/'
      preLoaderRoute: typeof LandingChangelogIndexRouteImport
      parentRoute: typeof LandingChangelogRoute
    }
    '/_landing/blog/': {
      id: '/_landing/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof LandingBlogIndexRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_dashboard/search/': {
      id: '/_dashboard/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof DashboardSearchIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/me/': {
      id: '/_dashboard/me/'
      path: '/me'
      fullPath: '/me/'
      preLoaderRoute: typeof DashboardMeIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/exports/': {
      id: '/_dashboard/exports/'
      path: '/exports'
      fullPath: '/exports/'
      preLoaderRoute: typeof DashboardExportsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/search/builders': {
      id: '/api/search/builders'
      path: '/api/search/builders'
      fullPath: '/api/search/builders'
      preLoaderRoute: typeof ApiSearchBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/request-upgrade': {
      id: '/api/plans/request-upgrade'
      path: '/api/plans/request-upgrade'
      fullPath: '/api/plans/request-upgrade'
      preLoaderRoute: typeof ApiPlansRequestUpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plans/me': {
      id: '/api/plans/me'
      path: '/api/plans/me'
      fullPath: '/api/plans/me'
      preLoaderRoute: typeof ApiPlansMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/status': {
      id: '/api/onboarding/status'
      path: '/api/onboarding/status'
      fullPath: '/api/onboarding/status'
      preLoaderRoute: typeof ApiOnboardingStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/skip': {
      id: '/api/onboarding/skip'
      path: '/api/onboarding/skip'
      fullPath: '/api/onboarding/skip'
      preLoaderRoute: typeof ApiOnboardingSkipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/complete': {
      id: '/api/onboarding/complete'
      path: '/api/onboarding/complete'
      fullPath: '/api/onboarding/complete'
      preLoaderRoute: typeof ApiOnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/explore': {
      id: '/api/og/explore'
      path: '/api/og/explore'
      fullPath: '/api/og/explore'
      preLoaderRoute: typeof ApiOgExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feeds/$searchId': {
      id: '/api/feeds/$searchId'
      path: '/api/feeds/$searchId'
      fullPath: '/api/feeds/$searchId'
      preLoaderRoute: typeof ApiFeedsSearchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export/builders': {
      id: '/api/export/builders'
      path: '/api/export/builders'
      fullPath: '/api/export/builders'
      preLoaderRoute: typeof ApiExportBuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dashboard/stats': {
      id: '/api/dashboard/stats'
      path: '/api/dashboard/stats'
      fullPath: '/api/dashboard/stats'
      preLoaderRoute: typeof ApiDashboardStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/changelog/$slug': {
      id: '/api/changelog/$slug'
      path: '/api/changelog/$slug'
      fullPath: '/api/changelog/$slug'
      preLoaderRoute: typeof ApiChangelogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builders/track': {
      id: '/api/builders/track'
      path: '/api/builders/track'
      fullPath: '/api/builders/track'
      preLoaderRoute: typeof ApiBuildersTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builders/$builderId': {
      id: '/api/builders/$builderId'
      path: '/api/builders/$builderId'
      fullPath: '/api/builders/$builderId'
      preLoaderRoute: typeof ApiBuildersBuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/test-trigger': {
      id: '/api/alerts/test-trigger'
      path: '/api/alerts/test-trigger'
      fullPath: '/api/alerts/test-trigger'
      preLoaderRoute: typeof ApiAlertsTestTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/legal/terms': {
      id: '/_landing/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LandingLegalTermsRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/legal/privacy': {
      id: '/_landing/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LandingLegalPrivacyRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/legal/imprint': {
      id: '/_landing/legal/imprint'
      path: '/legal/imprint'
      fullPath: '/legal/imprint'
      preLoaderRoute: typeof LandingLegalImprintRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/legal/cookies': {
      id: '/_landing/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LandingLegalCookiesRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_landing/changelog/$slug': {
      id: '/_landing/changelog/$slug'
      path: '/$slug'
      fullPath: '/changelog/$slug'
      preLoaderRoute: typeof LandingChangelogSlugRouteImport
      parentRoute: typeof LandingChangelogRoute
    }
    '/_landing/blog/$slug': {
      id: '/_landing/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof LandingBlogSlugRouteImport
      parentRoute: typeof LandingRouteRoute
    }
    '/_dashboard/settings/privacy': {
      id: '/_dashboard/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof DashboardSettingsPrivacyRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/settings/billing': {
      id: '/_dashboard/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof DashboardSettingsBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/admin/users': {
      id: '/_dashboard/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/admin/roadmap': {
      id: '/_dashboard/admin/roadmap'
      path: '/admin/roadmap'
      fullPath: '/admin/roadmap'
      preLoaderRoute: typeof DashboardAdminRoadmapRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/admin/plan-requests': {
      id: '/_dashboard/admin/plan-requests'
      path: '/admin/plan-requests'
      fullPath: '/admin/plan-requests'
      preLoaderRoute: typeof DashboardAdminPlanRequestsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/admin/metrics': {
      id: '/_dashboard/admin/metrics'
      path: '/admin/metrics'
      fullPath: '/admin/metrics'
      preLoaderRoute: typeof DashboardAdminMetricsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/admin/incidents': {
      id: '/_dashboard/admin/incidents'
      path: '/admin/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof DashboardAdminIncidentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/admin/changelog': {
      id: '/_dashboard/admin/changelog'
      path: '/admin/changelog'
      fullPath: '/admin/changelog'
      preLoaderRoute: typeof DashboardAdminChangelogRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/me/plan-changes/': {
      id: '/api/me/plan-changes/'
      path: '/api/me/plan-changes'
      fullPath: '/api/me/plan-changes/'
      preLoaderRoute: typeof ApiMePlanChangesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/delete-account/': {
      id: '/api/me/delete-account/'
      path: '/api/me/delete-account'
      fullPath: '/api/me/delete-account/'
      preLoaderRoute: typeof ApiMeDeleteAccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/data-export/': {
      id: '/api/me/data-export/'
      path: '/api/me/data-export'
      fullPath: '/api/me/data-export/'
      preLoaderRoute: typeof ApiMeDataExportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/builders/': {
      id: '/api/me/builders/'
      path: '/api/me/builders'
      fullPath: '/api/me/builders/'
      preLoaderRoute: typeof ApiMeBuildersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/builder/': {
      id: '/api/me/builder/'
      path: '/api/me/builder'
      fullPath: '/api/me/builder/'
      preLoaderRoute: typeof ApiMeBuilderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builders/recent/': {
      id: '/api/builders/recent/'
      path: '/api/builders/recent'
      fullPath: '/api/builders/recent/'
      preLoaderRoute: typeof ApiBuildersRecentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/alerts/triggers/': {
      id: '/api/alerts/triggers/'
      path: '/api/alerts/triggers'
      fullPath: '/api/alerts/triggers/'
      preLoaderRoute: typeof ApiAlertsTriggersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/': {
      id: '/api/admin/users/'
      path: '/api/admin/users'
      fullPath: '/api/admin/users/'
      preLoaderRoute: typeof ApiAdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/roadmap/': {
      id: '/api/admin/roadmap/'
      path: '/api/admin/roadmap'
      fullPath: '/api/admin/roadmap/'
      preLoaderRoute: typeof ApiAdminRoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/plan-requests/': {
      id: '/api/admin/plan-requests/'
      path: '/api/admin/plan-requests'
      fullPath: '/api/admin/plan-requests/'
      preLoaderRoute: typeof ApiAdminPlanRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/metrics/': {
      id: '/api/admin/metrics/'
      path: '/api/admin/metrics'
      fullPath: '/api/admin/metrics/'
      preLoaderRoute: typeof ApiAdminMetricsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/incidents/': {
      id: '/api/admin/incidents/'
      path: '/api/admin/incidents'
      fullPath: '/api/admin/incidents/'
      preLoaderRoute: typeof ApiAdminIncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/changelog/': {
      id: '/api/admin/changelog/'
      path: '/api/admin/changelog'
      fullPath: '/api/admin/changelog/'
      preLoaderRoute: typeof ApiAdminChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/builder/$builderId/': {
      id: '/_dashboard/builder/$builderId/'
      path: '/builder/$builderId'
      fullPath: '/builder/$builderId/'
      preLoaderRoute: typeof DashboardBuilderBuilderIdIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/me/data-export/$id': {
      id: '/api/me/data-export/$id'
      path: '/api/me/data-export/$id'
      fullPath: '/api/me/data-export/$id'
      preLoaderRoute: typeof ApiMeDataExportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me/builder/$builderId': {
      id: '/api/me/builder/$builderId'
      path: '/api/me/builder/$builderId'
      fullPath: '/api/me/builder/$builderId'
      preLoaderRoute: typeof ApiMeBuilderBuilderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builders/claim/verify': {
      id: '/api/builders/claim/verify'
      path: '/api/builders/claim/verify'
      fullPath: '/api/builders/claim/verify'
      preLoaderRoute: typeof ApiBuildersClaimVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/builders/$builderId/notes': {
      id: '/api/builders/$builderId/notes'
      path: '/notes'
      fullPath: '/api/builders/$builderId/notes'
      preLoaderRoute: typeof ApiBuildersBuilderIdNotesRouteImport
      parentRoute: typeof ApiBuildersBuilderIdRoute
    }
    '/api/builders/$builderId/claim': {
      id: '/api/builders/$builderId/claim'
      path: '/claim'
      fullPath: '/api/builders/$builderId/claim'
      preLoaderRoute: typeof ApiBuildersBuilderIdClaimRouteImport
      parentRoute: typeof ApiBuildersBuilderIdRoute
    }
    '/api/alerts/triggers/$id': {
      id: '/api/alerts/triggers/$id'
      path: '/api/alerts/triggers/$id'
      fullPath: '/api/alerts/triggers/$id'
      preLoaderRoute: typeof ApiAlertsTriggersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/$userId': {
      id: '/api/admin/users/$userId'
      path: '/api/admin/users/$userId'
      fullPath: '/api/admin/users/$userId'
      preLoaderRoute: typeof ApiAdminUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/roadmap/$id': {
      id: '/api/admin/roadmap/$id'
      path: '/api/admin/roadmap/$id'
      fullPath: '/api/admin/roadmap/$id'
      preLoaderRoute: typeof ApiAdminRoadmapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/incidents/$id': {
      id: '/api/admin/incidents/$id'
      path: '/api/admin/incidents/$id'
      fullPath: '/api/admin/incidents/$id'
      preLoaderRoute: typeof ApiAdminIncidentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/changelog/$id': {
      id: '/api/admin/changelog/$id'
      path: '/api/admin/changelog/$id'
      fullPath: '/api/admin/changelog/$id'
      preLoaderRoute: typeof ApiAdminChangelogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/alerts/run-worker': {
      id: '/api/admin/alerts/run-worker'
      path: '/api/admin/alerts/run-worker'
      fullPath: '/api/admin/alerts/run-worker'
      preLoaderRoute: typeof ApiAdminAlertsRunWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAlertsRoute: typeof DashboardAlertsRoute
  DashboardAdminChangelogRoute: typeof DashboardAdminChangelogRoute
  DashboardAdminIncidentsRoute: typeof DashboardAdminIncidentsRoute
  DashboardAdminMetricsRoute: typeof DashboardAdminMetricsRoute
  DashboardAdminPlanRequestsRoute: typeof DashboardAdminPlanRequestsRoute
  DashboardAdminRoadmapRoute: typeof DashboardAdminRoadmapRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardSettingsBillingRoute: typeof DashboardSettingsBillingRoute
  DashboardSettingsPrivacyRoute: typeof DashboardSettingsPrivacyRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
  DashboardExportsIndexRoute: typeof DashboardExportsIndexRoute
  DashboardMeIndexRoute: typeof DashboardMeIndexRoute
  DashboardSearchIndexRoute: typeof DashboardSearchIndexRoute
  DashboardBuilderBuilderIdIndexRoute: typeof DashboardBuilderBuilderIdIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAlertsRoute: DashboardAlertsRoute,
  DashboardAdminChangelogRoute: DashboardAdminChangelogRoute,
  DashboardAdminIncidentsRoute: DashboardAdminIncidentsRoute,
  DashboardAdminMetricsRoute: DashboardAdminMetricsRoute,
  DashboardAdminPlanRequestsRoute: DashboardAdminPlanRequestsRoute,
  DashboardAdminRoadmapRoute: DashboardAdminRoadmapRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardSettingsBillingRoute: DashboardSettingsBillingRoute,
  DashboardSettingsPrivacyRoute: DashboardSettingsPrivacyRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
  DashboardExportsIndexRoute: DashboardExportsIndexRoute,
  DashboardMeIndexRoute: DashboardMeIndexRoute,
  DashboardSearchIndexRoute: DashboardSearchIndexRoute,
  DashboardBuilderBuilderIdIndexRoute: DashboardBuilderBuilderIdIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LandingChangelogRouteChildren {
  LandingChangelogSlugRoute: typeof LandingChangelogSlugRoute
  LandingChangelogIndexRoute: typeof LandingChangelogIndexRoute
}

const LandingChangelogRouteChildren: LandingChangelogRouteChildren = {
  LandingChangelogSlugRoute: LandingChangelogSlugRoute,
  LandingChangelogIndexRoute: LandingChangelogIndexRoute,
}

const LandingChangelogRouteWithChildren =
  LandingChangelogRoute._addFileChildren(LandingChangelogRouteChildren)

interface LandingRouteRouteChildren {
  LandingChangelogRoute: typeof LandingChangelogRouteWithChildren
  LandingPricingRoute: typeof LandingPricingRoute
  LandingRoadmapRoute: typeof LandingRoadmapRoute
  LandingStatusRoute: typeof LandingStatusRoute
  LandingIndexRoute: typeof LandingIndexRoute
  LandingBlogSlugRoute: typeof LandingBlogSlugRoute
  LandingLegalCookiesRoute: typeof LandingLegalCookiesRoute
  LandingLegalImprintRoute: typeof LandingLegalImprintRoute
  LandingLegalPrivacyRoute: typeof LandingLegalPrivacyRoute
  LandingLegalTermsRoute: typeof LandingLegalTermsRoute
  LandingBlogIndexRoute: typeof LandingBlogIndexRoute
  LandingExploreIndexRoute: typeof LandingExploreIndexRoute
}

const LandingRouteRouteChildren: LandingRouteRouteChildren = {
  LandingChangelogRoute: LandingChangelogRouteWithChildren,
  LandingPricingRoute: LandingPricingRoute,
  LandingRoadmapRoute: LandingRoadmapRoute,
  LandingStatusRoute: LandingStatusRoute,
  LandingIndexRoute: LandingIndexRoute,
  LandingBlogSlugRoute: LandingBlogSlugRoute,
  LandingLegalCookiesRoute: LandingLegalCookiesRoute,
  LandingLegalImprintRoute: LandingLegalImprintRoute,
  LandingLegalPrivacyRoute: LandingLegalPrivacyRoute,
  LandingLegalTermsRoute: LandingLegalTermsRoute,
  LandingBlogIndexRoute: LandingBlogIndexRoute,
  LandingExploreIndexRoute: LandingExploreIndexRoute,
}

const LandingRouteRouteWithChildren = LandingRouteRoute._addFileChildren(
  LandingRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ApiBuildersBuilderIdRouteChildren {
  ApiBuildersBuilderIdClaimRoute: typeof ApiBuildersBuilderIdClaimRoute
  ApiBuildersBuilderIdNotesRoute: typeof ApiBuildersBuilderIdNotesRoute
}

const ApiBuildersBuilderIdRouteChildren: ApiBuildersBuilderIdRouteChildren = {
  ApiBuildersBuilderIdClaimRoute: ApiBuildersBuilderIdClaimRoute,
  ApiBuildersBuilderIdNotesRoute: ApiBuildersBuilderIdNotesRoute,
}

const ApiBuildersBuilderIdRouteWithChildren =
  ApiBuildersBuilderIdRoute._addFileChildren(ApiBuildersBuilderIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LandingRouteRoute: LandingRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthRoute: ApiHealthRoute,
  BlogAtomDotxmlRoute: BlogAtomDotxmlRoute,
  BuildersBuilderIdRoute: BuildersBuilderIdRoute,
  OnboardingSaveRoute: OnboardingSaveRoute,
  OnboardingSearchRoute: OnboardingSearchRoute,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  ApiAlertsTestTriggerRoute: ApiAlertsTestTriggerRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBuildersBuilderIdRoute: ApiBuildersBuilderIdRouteWithChildren,
  ApiBuildersTrackRoute: ApiBuildersTrackRoute,
  ApiChangelogSlugRoute: ApiChangelogSlugRoute,
  ApiDashboardStatsRoute: ApiDashboardStatsRoute,
  ApiExportBuildersRoute: ApiExportBuildersRoute,
  ApiFeedsSearchIdRoute: ApiFeedsSearchIdRoute,
  ApiOgExploreRoute: ApiOgExploreRoute,
  ApiOnboardingCompleteRoute: ApiOnboardingCompleteRoute,
  ApiOnboardingSkipRoute: ApiOnboardingSkipRoute,
  ApiOnboardingStatusRoute: ApiOnboardingStatusRoute,
  ApiPlansMeRoute: ApiPlansMeRoute,
  ApiPlansRequestUpgradeRoute: ApiPlansRequestUpgradeRoute,
  ApiSearchBuildersRoute: ApiSearchBuildersRoute,
  ApiAlertsIndexRoute: ApiAlertsIndexRoute,
  ApiChangelogIndexRoute: ApiChangelogIndexRoute,
  ApiConsentIndexRoute: ApiConsentIndexRoute,
  ApiIncidentsIndexRoute: ApiIncidentsIndexRoute,
  ApiQueriesIndexRoute: ApiQueriesIndexRoute,
  ApiRecommendationsIndexRoute: ApiRecommendationsIndexRoute,
  ApiRoadmapIndexRoute: ApiRoadmapIndexRoute,
  ApiStatusIndexRoute: ApiStatusIndexRoute,
  ApiAdminAlertsRunWorkerRoute: ApiAdminAlertsRunWorkerRoute,
  ApiAdminChangelogIdRoute: ApiAdminChangelogIdRoute,
  ApiAdminIncidentsIdRoute: ApiAdminIncidentsIdRoute,
  ApiAdminRoadmapIdRoute: ApiAdminRoadmapIdRoute,
  ApiAdminUsersUserIdRoute: ApiAdminUsersUserIdRoute,
  ApiAlertsTriggersIdRoute: ApiAlertsTriggersIdRoute,
  ApiBuildersClaimVerifyRoute: ApiBuildersClaimVerifyRoute,
  ApiMeBuilderBuilderIdRoute: ApiMeBuilderBuilderIdRoute,
  ApiMeDataExportIdRoute: ApiMeDataExportIdRoute,
  ApiAdminChangelogIndexRoute: ApiAdminChangelogIndexRoute,
  ApiAdminIncidentsIndexRoute: ApiAdminIncidentsIndexRoute,
  ApiAdminMetricsIndexRoute: ApiAdminMetricsIndexRoute,
  ApiAdminPlanRequestsIndexRoute: ApiAdminPlanRequestsIndexRoute,
  ApiAdminRoadmapIndexRoute: ApiAdminRoadmapIndexRoute,
  ApiAdminUsersIndexRoute: ApiAdminUsersIndexRoute,
  ApiAlertsTriggersIndexRoute: ApiAlertsTriggersIndexRoute,
  ApiBuildersRecentIndexRoute: ApiBuildersRecentIndexRoute,
  ApiMeBuilderIndexRoute: ApiMeBuilderIndexRoute,
  ApiMeBuildersIndexRoute: ApiMeBuildersIndexRoute,
  ApiMeDataExportIndexRoute: ApiMeDataExportIndexRoute,
  ApiMeDeleteAccountIndexRoute: ApiMeDeleteAccountIndexRoute,
  ApiMePlanChangesIndexRoute: ApiMePlanChangesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
